import '../../../core/models/fish_species.dart';

/// freshwaterGeneral 鱼种数据
class FreshwaterGeneralSpecies {
  FreshwaterGeneralSpecies._();

  static const List<FishSpecies> data = [
    const FishSpecies(
    id: 'g001',
    standardName: '鲤鱼',
    scientificName: 'Cyprinus carpio',
    aliases: ['鲤拐子', '锦鲤'],
    category: FishCategory.freshwaterGeneral,
    rarity: FishRarity.common,
    habitat: '江河、湖泊、池塘',
    behavior: '杂食性，底栖',
    fishingMethod: '玉米、面饵、蚯蚓',
    description: '常见淡水鱼，品种繁多',
    iconEmoji: '🐉',
    ),
    const FishSpecies(
    id: 'g002',
    standardName: '鲫鱼',
    scientificName: 'Carassius auratus',
    aliases: ['鲫瓜子'],
    category: FishCategory.freshwaterGeneral,
    rarity: FishRarity.common,
    habitat: '江河、湖泊、池塘',
    behavior: '杂食性，适应性强',
    fishingMethod: '蚯蚓、红虫、面饵',
    description: '最常见的淡水鱼之一',
    iconEmoji: '🐟',
    ),
    const FishSpecies(
    id: 'g003',
    standardName: '草鱼',
    scientificName: 'Ctenopharyngodon idella',
    aliases: ['草鲩', '厚子鱼'],
    category: FishCategory.freshwaterGeneral,
    rarity: FishRarity.common,
    habitat: '江河、湖泊、池塘',
    behavior: '草食性',
    fishingMethod: '草饵、蔬菜、玉米',
    description: '体型大，生长快',
    iconEmoji: '🐉',
    ),
    const FishSpecies(
    id: 'g004',
    standardName: '青鱼',
    scientificName: 'Mylopharyngodon piceus',
    aliases: ['青鲩', '螺蛳青'],
    category: FishCategory.freshwaterGeneral,
    rarity: FishRarity.uncommon,
    habitat: '江河、湖泊',
    behavior: '肉食性偏杂',
    fishingMethod: '螺蛳、蚌肉、玉米',
    description: '喜食贝类',
    iconEmoji: '🐉',
    ),
    const FishSpecies(
    id: 'g005',
    standardName: '鲢鱼',
    scientificName: 'Hypophthalmichthys molitrix',
    aliases: ['白鲢', '鲢子'],
    category: FishCategory.freshwaterGeneral,
    rarity: FishRarity.common,
    habitat: '江河、湖泊、池塘',
    behavior: '滤食性，喜群居',
    fishingMethod: '面饵、酸臭饵',
    description: '性活泼，善跳跃',
    iconEmoji: '🐟',
    ),
    const FishSpecies(
    id: 'g006',
    standardName: '鳙鱼',
    scientificName: 'Hypophthalmichthys nobilis',
    aliases: ['花鲢', '胖头鱼'],
    category: FishCategory.freshwaterGeneral,
    rarity: FishRarity.common,
    habitat: '江河、湖泊',
    behavior: '滤食性',
    fishingMethod: '面饵、酸臭饵',
    description: '头部较大',
    iconEmoji: '🐟',
    ),
    const FishSpecies(
    id: 'g007',
    standardName: '鳜鱼',
    scientificName: 'Siniperca chuatsi',
    aliases: ['桂鱼'],
    category: FishCategory.freshwaterGeneral,
    rarity: FishRarity.common,
    habitat: '江河、湖泊',
    behavior: '肉食性，伏击',
    fishingMethod: '活饵、软饵',
    description: '常见淡水肉食鱼',
    iconEmoji: '🐟',
    ),
    const FishSpecies(
    id: 'g008',
    standardName: '鲇鱼',
    scientificName: 'Silurus asotus',
    aliases: ['土鲇'],
    category: FishCategory.freshwaterGeneral,
    rarity: FishRarity.common,
    habitat: '江河、池塘',
    behavior: '肉食性，夜行',
    fishingMethod: '活饵、蚯蚓',
    description: '常见底层鱼类',
    iconEmoji: '🐱',
    ),
    const FishSpecies(
    id: 'g010',
    standardName: '罗非鱼',
    scientificName: 'Tilapia spp.',
    aliases: ['非洲鲫'],
    category: FishCategory.freshwaterGeneral,
    rarity: FishRarity.uncommon,
    habitat: '南方淡水',
    behavior: '杂食性，适应性强',
    fishingMethod: '面饵、玉米',
    description: '外来物种，繁殖快',
    iconEmoji: '🐟',
    ),
    const FishSpecies(
    id: 'g011',
    standardName: '鲮鱼',
    scientificName: 'Cirrhinus molitorella',
    aliases: ['土鲮'],
    category: FishCategory.freshwaterGeneral,
    rarity: FishRarity.uncommon,
    habitat: '南方淡水',
    behavior: '杂食性，底栖',
    fishingMethod: '面饵、玉米',
    description: '华南地区常见鱼',
    iconEmoji: '🐟',
    ),
    const FishSpecies(
    id: 'g012',
    standardName: '鳜鱼',
    scientificName: 'Butis spp.',
    aliases: ['笋壳鱼'],
    category: FishCategory.freshwaterGeneral,
    rarity: FishRarity.rare,
    habitat: '南方淡水',
    behavior: '肉食性',
    fishingMethod: '活饵、软饵',
    description: '笋壳鱼的一种',
    iconEmoji: '🐟',
    ),
    const FishSpecies(
    id: 'g013',
    standardName: '溪石斑',
    scientificName: 'Roccus saxatilis',
    aliases: ['石斑鱼'],
    category: FishCategory.freshwaterGeneral,
    rarity: FishRarity.rare,
    habitat: '山涧溪流',
    behavior: '肉食性',
    fishingMethod: '虫饵、软饵',
    description: '引进的冷水鱼',
    iconEmoji: '🐟',
    ),
    const FishSpecies(
    id: 'g014',
    standardName: '红眼马口',
    scientificName: 'Opsariichthys spp.',
    aliases: ['马口鱼'],
    category: FishCategory.freshwaterGeneral,
    rarity: FishRarity.uncommon,
    habitat: '溪流',
    behavior: '肉食性',
    fishingMethod: '虫饵、飞蝇',
    description: '眼睛呈红色',
    iconEmoji: '🐟',
    ),
    const FishSpecies(
    id: 'g016',
    standardName: '河鲤',
    scientificName: 'Cyprinus spp.',
    aliases: ['草鲤'],
    category: FishCategory.freshwaterGeneral,
    rarity: FishRarity.uncommon,
    habitat: '江河、湖泊',
    behavior: '杂食性',
    fishingMethod: '玉米、面饵',
    description: '野生状态的鲤鱼',
    iconEmoji: '🐉',
    ),
    const FishSpecies(
    id: 'g017',
    standardName: '青鲇',
    scientificName: null,
    aliases: ['青鱼'],
    category: FishCategory.freshwaterGeneral,
    rarity: FishRarity.uncommon,
    habitat: '江河、湖泊',
    behavior: '肉食性',
    fishingMethod: '活饵、软饵',
    description: '青色系大型鱼',
    iconEmoji: '🐉',
    ),
    const FishSpecies(
    id: 'g019',
    standardName: '凤鲚',
    scientificName: 'Coilia nasus',
    aliases: ['凤尾鱼'],
    category: FishCategory.freshwaterGeneral,
    rarity: FishRarity.uncommon,
    habitat: '长江口',
    behavior: '肉食性',
    fishingMethod: '虫饵',
    description: '刀鱼的一种',
    iconEmoji: '🐟',
    ),
    const FishSpecies(
    id: 'g022',
    standardName: '鲟鱼',
    scientificName: 'Acipenser sinensis',
    aliases: ['中华鲟'],
    category: FishCategory.freshwaterGeneral,
    rarity: FishRarity.legendary,
    habitat: '长江',
    behavior: '肉食性',
    fishingMethod: '活饵',
    description: '国家一级保护动物',
    iconEmoji: '🦈',
    ),
    const FishSpecies(
    id: 'g023',
    standardName: '鳜鱼',
    scientificName: 'Siniperca scherzeri',
    aliases: ['多鳞鳜'],
    category: FishCategory.freshwaterGeneral,
    rarity: FishRarity.rare,
    habitat: '山涧溪流',
    behavior: '肉食性',
    fishingMethod: '活饵、软饵',
    description: '小型鳜鱼',
    iconEmoji: '🐟',
    ),
    const FishSpecies(
    id: 'g024',
    standardName: '沙塘鳢',
    scientificName: 'Odontobutis obscura',
    aliases: ['沙龟'],
    category: FishCategory.freshwaterGeneral,
    rarity: FishRarity.uncommon,
    habitat: '淡水溪流',
    behavior: '肉食性',
    fishingMethod: '虫饵',
    description: '小型淡水鱼',
    iconEmoji: '🐟',
    ),
    const FishSpecies(
    id: 'g025',
    standardName: '黄鳝',
    scientificName: 'Monopterus albus',
    aliases: ['鳝鱼'],
    category: FishCategory.freshwaterGeneral,
    rarity: FishRarity.uncommon,
    habitat: '稻田、池塘',
    behavior: '肉食性，夜行',
    fishingMethod: '蚯蚓、软饵',
    description: '无鳞淡水鱼',
    iconEmoji: '🐍',
    ),
    const FishSpecies(
    id: 'g026',
    standardName: '鳗鲡',
    scientificName: 'Anguilla japonica',
    aliases: ['鳗鱼'],
    category: FishCategory.freshwaterGeneral,
    rarity: FishRarity.rare,
    habitat: '江河入海口',
    behavior: '肉食性',
    fishingMethod: '活饵、软饵',
    description: '洄游性鱼类',
    iconEmoji: '🐍',
    ),
    const FishSpecies(
    id: 'g027',
    standardName: '河鳗',
    scientificName: 'Anguilla japonica',
    aliases: ['白鳝'],
    category: FishCategory.freshwaterGeneral,
    rarity: FishRarity.rare,
    habitat: '淡水流域',
    behavior: '肉食性',
    fishingMethod: '活饵',
    description: '鳗鲡的淡水形态',
    iconEmoji: '🐍',
    ),
    const FishSpecies(
    id: 'g029',
    standardName: '凤尾鱼',
    scientificName: 'Coilia nasus',
    aliases: [],
    category: FishCategory.freshwaterGeneral,
    rarity: FishRarity.uncommon,
    habitat: '长江口',
    behavior: '杂食性',
    fishingMethod: '虫饵',
    description: '常见小型鱼',
    iconEmoji: '🐟',
    ),
    const FishSpecies(
    id: 'g031',
    standardName: '弹涂鱼',
    scientificName: 'Periophthalmus spp.',
    aliases: ['跳跳鱼'],
    category: FishCategory.freshwaterGeneral,
    rarity: FishRarity.rare,
    habitat: '滩涂、河口',
    behavior: '杂食性，可离水',
    fishingMethod: '虫饵',
    description: '能爬行跳跃',
    iconEmoji: '🐸',
    ),
    const FishSpecies(
    id: 'g032',
    standardName: '斗鱼',
    scientificName: 'Macropodus opercularis',
    aliases: ['中国斗鱼'],
    category: FishCategory.freshwaterGeneral,
    rarity: FishRarity.uncommon,
    habitat: '稻田、池塘',
    behavior: '杂食性',
    fishingMethod: '虫饵',
    description: '色彩艳丽的小型鱼',
    iconEmoji: '🐟',
    ),
    const FishSpecies(
    id: 'g033',
    standardName: '刺鳅',
    scientificName: 'Mastacembelus aculeatus',
    aliases: ['刀鳅'],
    category: FishCategory.freshwaterGeneral,
    rarity: FishRarity.uncommon,
    habitat: '南方淡水',
    behavior: '杂食性',
    fishingMethod: '虫饵',
    description: '背鳍有刺',
    iconEmoji: '🐍',
    ),
    const FishSpecies(
    id: 'g034',
    standardName: '鳜鱼',
    scientificName: 'Siniperca scherzeri',
    aliases: ['大眼鳜'],
    category: FishCategory.freshwaterGeneral,
    rarity: FishRarity.rare,
    habitat: '山涧溪流',
    behavior: '肉食性',
    fishingMethod: '活饵、软饵',
    description: '眼睛较大',
    iconEmoji: '🐟',
    ),
    const FishSpecies(
    id: 'g035',
    standardName: '暗纹东方鲀',
    scientificName: 'Takifugu fasciatus',
    aliases: ['河豚'],
    category: FishCategory.freshwaterGeneral,
    rarity: FishRarity.rare,
    habitat: '江河、河口',
    behavior: '肉食性，受惊充气',
    fishingMethod: '软饵',
    description: '有河豚毒素',
    iconEmoji: '🐡',
    ),
    const FishSpecies(
    id: 'g042',
    standardName: '中颌鲑鲤',
    scientificName: 'Rafael & Goodes',
    aliases: [],
    category: FishCategory.freshwaterGeneral,
    rarity: FishRarity.rare,
    habitat: '淡水',
    behavior: '杂食性',
    fishingMethod: '软饵',
    description: '中型淡水鱼',
    iconEmoji: '🐟',
    ),
    const FishSpecies(
    id: 'g043',
    standardName: '圆口铜鱼',
    scientificName: 'Coreius guichenoti',
    aliases: ['铜鱼'],
    category: FishCategory.freshwaterGeneral,
    rarity: FishRarity.uncommon,
    habitat: '长江上游',
    behavior: '杂食性',
    fishingMethod: '虫饵',
    description: '体色铜黄',
    iconEmoji: '🐟',
    ),
    const FishSpecies(
    id: 'g044',
    standardName: '中华细鲫',
    scientificName: 'Aphyocypris chinensis',
    aliases: ['草鱼苗'],
    category: FishCategory.freshwaterGeneral,
    rarity: FishRarity.common,
    habitat: '南方淡水',
    behavior: '杂食性',
    fishingMethod: '虫饵',
    description: '常见小型淡水鱼',
    iconEmoji: '🐟',
    ),
    const FishSpecies(
    id: 'g045',
    standardName: '须鲫',
    scientificName: 'Carassius carassius',
    aliases: ['野生鲫鱼'],
    category: FishCategory.freshwaterGeneral,
    rarity: FishRarity.uncommon,
    habitat: '江河、湖泊',
    behavior: '杂食性',
    fishingMethod: '蚯蚓、红虫',
    description: '口须明显',
    iconEmoji: '🐟',
    ),
    const FishSpecies(
    id: 'g050',
    standardName: '弓斑东方鲀',
    scientificName: 'Takifugu ocellatus',
    aliases: ['河豚'],
    category: FishCategory.freshwaterGeneral,
    rarity: FishRarity.rare,
    habitat: '江河入海口',
    behavior: '肉食性',
    fishingMethod: '软饵',
    description: '眼部有斑纹',
    iconEmoji: '🐡',
    ),
  ];
}
