import '../../../core/models/fish_species.dart';

/// freshwaterLure 鱼种数据
class FreshwaterLureSpecies {
  FreshwaterLureSpecies._();

  static const List<FishSpecies> data = [
    const FishSpecies(
    id: 'f001',
    standardName: '鳜鱼',
    scientificName: 'Siniperca chuatsi',
    aliases: ['桂鱼', '桂花鱼', '鳜花', '翘嘴鳜'],
    category: FishCategory.freshwaterLure,
    rarity: FishRarity.rare,
    habitat: '江河、湖泊、水库',
    behavior: '肉食性鱼类，伏击型捕食',
    fishingMethod: '软饵、亮片、米诺',
    description: '典型肉食性淡水鱼，体侧有黑色斑点',
    iconEmoji: '🐟',
    ),
    const FishSpecies(
    id: 'f002',
    standardName: '大口黑鲈',
    scientificName: 'Micropterus salmoides',
    aliases: ['加拿大鳜鱼', '黑鲈'],
    category: FishCategory.freshwaterLure,
    rarity: FishRarity.uncommon,
    habitat: '湖泊、水库、河流',
    behavior: '肉食性，攻击性强',
    fishingMethod: '软饵、crankbait、spinnerbait',
    description: '原产北美，入侵我国的外来物种',
    iconEmoji: '🐠',
    ),
    const FishSpecies(
    id: 'f003',
    standardName: '河鲈',
    scientificName: 'Perca fluviatilis',
    aliases: ['五道黑'],
    category: FishCategory.freshwaterLure,
    rarity: FishRarity.rare,
    habitat: '江河、湖泊',
    behavior: '群居肉食性鱼类',
    fishingMethod: '亮片、小型软饵',
    description: '体侧有五道黑色横纹',
    iconEmoji: '🐟',
    ),
    const FishSpecies(
    id: 'f004',
    standardName: '乌鳢',
    scientificName: 'Channa argus',
    aliases: ['黑鱼', '财鱼', '生鱼', '斑鳢'],
    category: FishCategory.freshwaterLure,
    rarity: FishRarity.common,
    habitat: '池塘、湖泊、河流',
    behavior: '肉食性，伏击型，会护幼',
    fishingMethod: '软饵、面包虫',
    description: '适应能力强，能在缺氧环境中生存',
    iconEmoji: '🐍',
    ),
    const FishSpecies(
    id: 'f005',
    standardName: '斑鳢',
    scientificName: 'Channa maculata',
    aliases: ['斑鱼', '月鳢'],
    category: FishCategory.freshwaterLure,
    rarity: FishRarity.uncommon,
    habitat: '南方淡水流域',
    behavior: '肉食性，昼伏夜出',
    fishingMethod: '软饵、活饵',
    description: '与乌鳢相似，但花纹不同',
    iconEmoji: '🐟',
    ),
    const FishSpecies(
    id: 'f006',
    standardName: '翘嘴红鲌',
    scientificName: 'Culter alburnus',
    aliases: ['翘嘴', '大白鱼'],
    category: FishCategory.freshwaterLure,
    rarity: FishRarity.uncommon,
    habitat: '江河、湖泊',
    behavior: '肉食性，掠食游速快',
    fishingMethod: '亮片、米诺、波扒',
    description: '体型修长，嘴型上翘',
    iconEmoji: '🐟',
    ),
    const FishSpecies(
    id: 'f007',
    standardName: '蒙古红鲌',
    scientificName: 'Culter mongolicus',
    aliases: ['红梢', '小白鱼'],
    category: FishCategory.freshwaterLure,
    rarity: FishRarity.uncommon,
    habitat: '江河、湖泊',
    behavior: '群居小体型肉食性',
    fishingMethod: '小型亮片、软饵',
    description: '体型较小的红尾掠食鱼',
    iconEmoji: '🐟',
    ),
    const FishSpecies(
    id: 'f008',
    standardName: '黄颡鱼',
    scientificName: 'Pelteobagrus fulvidraco',
    aliases: ['黄辣丁', '昂刺鱼', '黄骨鱼'],
    category: FishCategory.freshwaterLure,
    rarity: FishRarity.uncommon,
    habitat: '江河、湖泊、池塘',
    behavior: '夜行性，底栖肉食性',
    fishingMethod: '软饵、虫饵',
    description: '体色金黄，有毒刺',
    iconEmoji: '🐟',
    ),
    const FishSpecies(
    id: 'f009',
    standardName: '瓦氏黄颡鱼',
    scientificName: 'Pelteobagrus vachelli',
    aliases: ['江黄颡'],
    category: FishCategory.freshwaterLure,
    rarity: FishRarity.rare,
    habitat: '长江流域',
    behavior: '底栖肉食性',
    fishingMethod: '软饵、虫饵',
    description: '体型比黄颡鱼大',
    iconEmoji: '🐟',
    ),
    const FishSpecies(
    id: 'f010',
    standardName: '斑点叉尾鮰',
    scientificName: 'Ictalurus punctatus',
    aliases: ['沟鲇', '钳鱼'],
    category: FishCategory.freshwaterLure,
    rarity: FishRarity.rare,
    habitat: '江河、湖泊、水库',
    behavior: '杂食性，适应性强',
    fishingMethod: '软饵、虫饵',
    description: '原产北美，我国引进养殖',
    iconEmoji: '🐟',
    ),
    const FishSpecies(
    id: 'f011',
    standardName: '革胡子鲇',
    scientificName: 'Clarias gariepinus',
    aliases: ['埃及塘鲺'],
    category: FishCategory.freshwaterLure,
    rarity: FishRarity.uncommon,
    habitat: '池塘、稻田',
    behavior: '杂食性，适应力极强',
    fishingMethod: '软饵、活饵',
    description: '外来物种，繁殖能力强',
    iconEmoji: '🐟',
    ),
    const FishSpecies(
    id: 'f012',
    standardName: '南方大口鲇',
    scientificName: 'Silurus meridionalis',
    aliases: ['土鲇', '大河鲇'],
    category: FishCategory.freshwaterLure,
    rarity: FishRarity.rare,
    habitat: '长江以南淡水流域',
    behavior: '肉食性，夜行性',
    fishingMethod: '大型软饵、活饵',
    description: '体型大，口裂大',
    iconEmoji: '🐟',
    ),
    const FishSpecies(
    id: 'f013',
    standardName: '北方大口鲇',
    scientificName: 'Silurus asotus',
    aliases: ['东北大口鲇'],
    category: FishCategory.freshwaterLure,
    rarity: FishRarity.rare,
    habitat: '东北地区淡水',
    behavior: '肉食性，夜行性',
    fishingMethod: '大型软饵、活饵',
    description: '北方特有大型鲇鱼',
    iconEmoji: '🐟',
    ),
    const FishSpecies(
    id: 'f014',
    standardName: '鲇鱼',
    scientificName: 'Silurus asotus',
    aliases: ['鲶鱼', '土鲇'],
    category: FishCategory.freshwaterLure,
    rarity: FishRarity.uncommon,
    habitat: '江河、湖泊、池塘',
    behavior: '肉食性，夜行性',
    fishingMethod: '软饵、虫饵',
    description: '体表无鳞，适应力强',
    iconEmoji: '🐱',
    ),
    const FishSpecies(
    id: 'f015',
    standardName: '马口鱼',
    scientificName: 'Opsariichthys bidens',
    aliases: ['马口', '宽鳍'],
    category: FishCategory.freshwaterLure,
    rarity: FishRarity.common,
    habitat: '清澈溪流',
    behavior: '群居，小型肉食性',
    fishingMethod: '小型亮片、飞蝇',
    description: '雄鱼婚姻色鲜艳',
    iconEmoji: '🐟',
    ),
    const FishSpecies(
    id: 'f016',
    standardName: '宽鳍鱲',
    scientificName: 'Zacco temminckii',
    aliases: ['桃花鱼', '红猫鱼'],
    category: FishCategory.freshwaterLure,
    rarity: FishRarity.uncommon,
    habitat: '山涧溪流',
    behavior: '群居，杂食性',
    fishingMethod: '小型亮片、飞蝇',
    description: '春季繁殖期体色艳丽',
    iconEmoji: '🐟',
    ),
    const FishSpecies(
    id: 'f017',
    standardName: '餐条',
    scientificName: 'Hemiculter leucisculus',
    aliases: ['白条', '餐子'],
    category: FishCategory.freshwaterLure,
    rarity: FishRarity.common,
    habitat: '湖泊、河流',
    behavior: '群居，杂食性',
    fishingMethod: '小型亮片、飞蝇',
    description: '常见小型鱼，数量多',
    iconEmoji: '🐟',
    ),
    const FishSpecies(
    id: 'f018',
    standardName: '红眼金线鱼',
    scientificName: 'Rhodeus sericeus',
    aliases: ['红眼', '金线'],
    category: FishCategory.freshwaterLure,
    rarity: FishRarity.rare,
    habitat: '静水或缓流',
    behavior: '杂食性，繁殖方式特殊',
    fishingMethod: '小型软饵',
    description: '眼睛呈红色',
    iconEmoji: '🐟',
    ),
    const FishSpecies(
    id: 'f019',
    standardName: '鳊鱼',
    scientificName: 'Parabramis pekinensis',
    aliases: ['长春鳊', '草鳊'],
    category: FishCategory.freshwaterLure,
    rarity: FishRarity.uncommon,
    habitat: '江河、湖泊',
    behavior: '草食性',
    fishingMethod: '素饵、面包',
    description: '体型侧扁，草食性',
    iconEmoji: '🐟',
    ),
    const FishSpecies(
    id: 'f020',
    standardName: '中华细鲫',
    scientificName: 'Aphyocypris chinensis',
    aliases: ['草鱼苗', '小白鲢'],
    category: FishCategory.freshwaterLure,
    rarity: FishRarity.uncommon,
    habitat: '南方淡水',
    behavior: '杂食性',
    fishingMethod: '小型软饵',
    description: '小型淡水鱼',
    iconEmoji: '🐟',
    ),
    const FishSpecies(
    id: 'f021',
    standardName: '蓝鳍鲫',
    scientificName: 'Cyprinus carpio',
    aliases: ['小金线'],
    category: FishCategory.freshwaterLure,
    rarity: FishRarity.uncommon,
    habitat: '淡水流域',
    behavior: '杂食性',
    fishingMethod: '软饵、谷物饵',
    description: '鳍条带蓝色',
    iconEmoji: '🐟',
    ),
    const FishSpecies(
    id: 'f022',
    standardName: '泥鳅',
    scientificName: 'Misgurnus anguillicaudatus',
    aliases: ['泥鳅鱼'],
    category: FishCategory.freshwaterLure,
    rarity: FishRarity.common,
    habitat: '池塘、稻田、河流',
    behavior: '杂食性，底栖',
    fishingMethod: '软饵、虫饵',
    description: '耐低氧，适应性强',
    iconEmoji: '🐍',
    ),
    const FishSpecies(
    id: 'f023',
    standardName: '黄鳝',
    scientificName: 'Monopterus albus',
    aliases: ['鳝鱼', '长鱼'],
    category: FishCategory.freshwaterLure,
    rarity: FishRarity.uncommon,
    habitat: '稻田、池塘、河流',
    behavior: '肉食性，夜行性',
    fishingMethod: '软饵、蚯蚓',
    description: '体型细长，无鳞',
    iconEmoji: '🐍',
    ),
    const FishSpecies(
    id: 'f024',
    standardName: '鳗鱼',
    scientificName: 'Anguilla japonica',
    aliases: ['河鳗', '白鳝'],
    category: FishCategory.freshwaterLure,
    rarity: FishRarity.rare,
    habitat: '江河入海口',
    behavior: '降海繁殖，肉食性',
    fishingMethod: '活饵、软饵',
    description: '洄游性鱼类',
    iconEmoji: '🐍',
    ),
    const FishSpecies(
    id: 'f025',
    standardName: '刀鱼',
    scientificName: 'Coilia nasus',
    aliases: ['凤尾鱼', '刀鲚'],
    category: FishCategory.freshwaterLure,
    rarity: FishRarity.rare,
    habitat: '长江中下游',
    behavior: '肉食性小型鱼',
    fishingMethod: '小型软饵',
    description: '体型侧扁如刀',
    iconEmoji: '🐟',
    ),
    const FishSpecies(
    id: 'f026',
    standardName: '河鲀',
    scientificName: 'Takifugu spp.',
    aliases: ['河豚', '气鼓鱼'],
    category: FishCategory.freshwaterLure,
    rarity: FishRarity.legendary,
    habitat: '江河入海口',
    behavior: '肉食性，受惊充气',
    fishingMethod: '软饵、活饵',
    description: '体内有河豚毒素',
    iconEmoji: '🐡',
    ),
    const FishSpecies(
    id: 'f027',
    standardName: '中华鲂',
    scientificName: 'Megalobrama amblycephala',
    aliases: ['武昌鱼', '团头鲂'],
    category: FishCategory.freshwaterLure,
    rarity: FishRarity.uncommon,
    habitat: '长江中下游',
    behavior: '草食性',
    fishingMethod: '素饵、蔬菜',
    description: '著名淡水养殖鱼',
    iconEmoji: '🐟',
    ),
    const FishSpecies(
    id: 'f028',
    standardName: '三角鲂',
    scientificName: 'Megalobrama terminalis',
    aliases: ['三角鳊'],
    category: FishCategory.freshwaterLure,
    rarity: FishRarity.uncommon,
    habitat: '江河、湖泊',
    behavior: '草食性',
    fishingMethod: '素饵',
    description: '体型呈三角形',
    iconEmoji: '🐟',
    ),
    const FishSpecies(
    id: 'f029',
    standardName: '虹鳟',
    scientificName: 'Oncorhynchus mykiss',
    aliases: ['虹鳟鱼'],
    category: FishCategory.freshwaterLure,
    rarity: FishRarity.legendary,
    habitat: '冷水溪流',
    behavior: '肉食性，喜冷水',
    fishingMethod: '飞蝇、亮片',
    description: '侧线有彩虹色斑纹',
    iconEmoji: '🐟',
    ),
    const FishSpecies(
    id: 'f030',
    standardName: '金鳟',
    scientificName: 'Oncorhynchus mykiss',
    aliases: [],
    category: FishCategory.freshwaterLure,
    rarity: FishRarity.legendary,
    habitat: '冷水溪流',
    behavior: '肉食性',
    fishingMethod: '飞蝇、亮片',
    description: '虹鳟的金色变异种',
    iconEmoji: '🐟',
    ),
    const FishSpecies(
    id: 'f031',
    standardName: '胭脂鱼',
    scientificName: 'Myxocyprinus asiaticus',
    aliases: ['火烧鳊', '一帆风顺'],
    category: FishCategory.freshwaterLure,
    rarity: FishRarity.legendary,
    habitat: '长江上游',
    behavior: '杂食性',
    fishingMethod: '软饵',
    description: '中国特有淡水鱼',
    iconEmoji: '🐟',
    ),
    const FishSpecies(
    id: 'f032',
    standardName: '鸭嘴鲇',
    scientificName: 'Polyodon spathula',
    aliases: ['鸭嘴鱼', '匙吻鲇'],
    category: FishCategory.freshwaterLure,
    rarity: FishRarity.legendary,
    habitat: '北美淡水',
    behavior: '滤食性',
    fishingMethod: '软饵',
    description: '原产北美，嘴呈鸭嘴状',
    iconEmoji: '🐟',
    ),
    const FishSpecies(
    id: 'f033',
    standardName: '中华鲟',
    scientificName: 'Acipenser sinensis',
    aliases: ['鳇鱼', '腊子'],
    category: FishCategory.freshwaterLure,
    rarity: FishRarity.mythical,
    habitat: '长江',
    behavior: '肉食性，洄游性',
    fishingMethod: '大型活饵',
    description: '国家一级保护动物',
    iconEmoji: '🦈',
    ),
    const FishSpecies(
    id: 'f034',
    standardName: '白鲟',
    scientificName: 'Psephurus gladius',
    aliases: ['象鱼', '棍子鱼'],
    category: FishCategory.freshwaterLure,
    rarity: FishRarity.mythical,
    habitat: '长江',
    behavior: '肉食性',
    fishingMethod: '大型活饵',
    description: '已功能性灭绝的巨型淡水鱼',
    iconEmoji: '🦈',
    ),
  ];
}
