import 'package:lurebox/core/models/fish_species.dart';

/// saltwaterGeneral 鱼种数据
class SaltwaterGeneralSpecies {
  SaltwaterGeneralSpecies._();

  static const List<FishSpecies> data = [
    FishSpecies(
    id: 'g009',
    standardName: '梭鱼',
    scientificName: 'Mugil cephalus',
    aliases: ['梭子鱼'],
    category: FishCategory.saltwaterGeneral,
    rarity: FishRarity.uncommon,
    habitat: '沿海河口',
    behavior: '杂食性',
    fishingMethod: '面饵、虫子',
    description: '可入淡水的海鱼',
    iconEmoji: '🐟',
    ),
    FishSpecies(
    id: 'g015',
    standardName: '柳叶鱼',
    scientificName: 'Engraulis japonicus',
    category: FishCategory.saltwaterGeneral,
    rarity: FishRarity.uncommon,
    habitat: '沿海海域',
    behavior: '杂食性',
    fishingMethod: '虫饵',
    description: '小型鱼',
    iconEmoji: '🐟',
    ),
    FishSpecies(
    id: 'g018',
    standardName: '银鲳',
    scientificName: 'Pampus argenteus',
    aliases: ['银鲳鱼'],
    category: FishCategory.saltwaterGeneral,
    rarity: FishRarity.uncommon,
    habitat: '沿海海域、河口',
    behavior: '杂食性',
    fishingMethod: '虫饵、软饵',
    description: '体型侧扁银白色',
    iconEmoji: '🐟',
    ),
    FishSpecies(
    id: 'g020',
    standardName: '斑鰶',
    scientificName: 'Konosirus punctatus',
    category: FishCategory.saltwaterGeneral,
    rarity: FishRarity.uncommon,
    habitat: '沿海海域',
    behavior: '杂食性',
    fishingMethod: '虫饵',
    description: '小型海水鱼',
    iconEmoji: '🐟',
    ),
    FishSpecies(
    id: 'g021',
    standardName: '舌鳎',
    scientificName: 'Solea spp.',
    aliases: ['鳎沙鱼'],
    category: FishCategory.saltwaterGeneral,
    rarity: FishRarity.rare,
    habitat: '沿海海域、河口',
    behavior: '底栖肉食性',
    fishingMethod: '虫饵',
    description: '体型扁平如舌',
    iconEmoji: '🐟',
    ),
    FishSpecies(
    id: 'g028',
    standardName: '七丝鲚',
    scientificName: 'Coilia grayii',
    category: FishCategory.saltwaterGeneral,
    rarity: FishRarity.uncommon,
    habitat: '沿海海域',
    behavior: '杂食性',
    fishingMethod: '虫饵',
    description: '小型鱼类',
    iconEmoji: '🐟',
    ),
    FishSpecies(
    id: 'g030',
    standardName: '遮目鱼',
    scientificName: 'Chanos chanos',
    aliases: ['虱目鱼'],
    category: FishCategory.saltwaterGeneral,
    rarity: FishRarity.rare,
    habitat: '热带沿海',
    behavior: '草食性',
    fishingMethod: '素饵',
    description: '重要养殖鱼种',
    iconEmoji: '🐟',
    ),
    FishSpecies(
    id: 'g036',
    standardName: '黄鳍东方鲀',
    scientificName: 'Takifugu xanthopterus',
    aliases: ['河豚'],
    category: FishCategory.saltwaterGeneral,
    rarity: FishRarity.rare,
    habitat: '沿海海域',
    behavior: '肉食性',
    fishingMethod: '软饵',
    description: '鳍条黄色',
    iconEmoji: '🐡',
    ),
    FishSpecies(
    id: 'g037',
    standardName: '菊黄东方鲀',
    scientificName: 'Takifugu flavidus',
    aliases: ['河豚'],
    category: FishCategory.saltwaterGeneral,
    rarity: FishRarity.legendary,
    habitat: '沿海海域',
    behavior: '肉食性',
    fishingMethod: '软饵',
    description: '体色菊黄',
    iconEmoji: '🐡',
    ),
    FishSpecies(
    id: 'g038',
    standardName: '斑点鸡笼鲳',
    scientificName: 'Drepane punctata',
    aliases: ['鲳鱼'],
    category: FishCategory.saltwaterGeneral,
    rarity: FishRarity.uncommon,
    habitat: '沿海海域',
    behavior: '杂食性',
    fishingMethod: '虫饵',
    description: '体有斑点',
    iconEmoji: '🐟',
    ),
    FishSpecies(
    id: 'g039',
    standardName: '灰鲳',
    scientificName: 'Pampus cinereus',
    aliases: ['鲳鱼'],
    category: FishCategory.saltwaterGeneral,
    rarity: FishRarity.uncommon,
    habitat: '沿海海域',
    behavior: '杂食性',
    fishingMethod: '虫饵、软饵',
    description: '体色灰白',
    iconEmoji: '🐟',
    ),
    FishSpecies(
    id: 'g040',
    standardName: '刺鲳',
    scientificName: 'Psenopsis anomala',
    aliases: ['鲳鱼'],
    category: FishCategory.saltwaterGeneral,
    rarity: FishRarity.uncommon,
    habitat: '沿海海域',
    behavior: '杂食性',
    fishingMethod: '虫饵',
    description: '背鳍有刺',
    iconEmoji: '🐟',
    ),
    FishSpecies(
    id: 'g041',
    standardName: '乌鲳',
    scientificName: 'Parastromateus niger',
    aliases: ['铁甲鲳'],
    category: FishCategory.saltwaterGeneral,
    rarity: FishRarity.uncommon,
    habitat: '热带海域',
    behavior: '杂食性',
    fishingMethod: '虫饵',
    description: '体色深灰',
    iconEmoji: '🐟',
    ),
    FishSpecies(
    id: 'g046',
    standardName: '短棘鲀',
    scientificName: 'Diodon spp.',
    aliases: ['刺河豚'],
    category: FishCategory.saltwaterGeneral,
    rarity: FishRarity.rare,
    habitat: '沿海海域',
    behavior: '杂食性，受惊充气',
    fishingMethod: '软饵',
    description: '体有短刺',
    iconEmoji: '🐡',
    ),
    FishSpecies(
    id: 'g047',
    standardName: '六斑刺鲀',
    scientificName: 'Diodon holocanthus',
    aliases: ['刺河豚'],
    category: FishCategory.saltwaterGeneral,
    rarity: FishRarity.rare,
    habitat: '热带海域',
    behavior: '杂食性',
    fishingMethod: '软饵',
    description: '体有六斑',
    iconEmoji: '🐡',
    ),
    FishSpecies(
    id: 'g048',
    standardName: '纹腹叉鼻鲀',
    scientificName: 'Arothron hispidus',
    aliases: ['气鼓鱼'],
    category: FishCategory.saltwaterGeneral,
    rarity: FishRarity.legendary,
    habitat: '热带海域',
    behavior: '杂食性',
    fishingMethod: '软饵',
    description: '腹部有纹',
    iconEmoji: '🐡',
    ),
    FishSpecies(
    id: 'g049',
    standardName: '星点东方鲀',
    scientificName: 'Takifugu niphyperion',
    aliases: ['河豚'],
    category: FishCategory.saltwaterGeneral,
    rarity: FishRarity.legendary,
    habitat: '沿海海域',
    behavior: '肉食性',
    fishingMethod: '软饵',
    description: '体有星点',
    iconEmoji: '🐡',
    ),
  ];
}
