import '../../../core/models/fish_species.dart';

/// saltwaterLure 鱼种数据
class SaltwaterLureSpecies {
  SaltwaterLureSpecies._();

  static const List<FishSpecies> data = [
    const FishSpecies(
    id: 'f035',
    standardName: '海鲈',
    scientificName: 'Lateolabrax japonicus',
    aliases: ['七星鲈', '花鲈'],
    category: FishCategory.saltwaterLure,
    rarity: FishRarity.uncommon,
    habitat: '沿海海域、河口',
    behavior: '肉食性，洄游',
    fishingMethod: '软饵、亮片、米诺',
    description: '可入淡水的海产鱼',
    iconEmoji: '🐟',
    ),
    const FishSpecies(
    id: 'f036',
    standardName: '黑鲷',
    scientificName: 'Acanthopagrus schlegelii',
    aliases: ['海鲋', '黑棘鲷'],
    category: FishCategory.saltwaterLure,
    rarity: FishRarity.rare,
    habitat: '沿海海域、礁石区',
    behavior: '杂食性，地域性强',
    fishingMethod: '软饵、活饵',
    description: '高级海钓鱼种',
    iconEmoji: '🐟',
    ),
    const FishSpecies(
    id: 'f037',
    standardName: '真鲷',
    scientificName: 'Pagrus major',
    aliases: ['加计鱼', '红鲷'],
    category: FishCategory.saltwaterLure,
    rarity: FishRarity.legendary,
    habitat: '沿海海域',
    behavior: '杂食性',
    fishingMethod: '软饵、活饵',
    description: '海钓中的珍贵鱼种',
    iconEmoji: '🐟',
    ),
    const FishSpecies(
    id: 'f038',
    standardName: '石斑鱼',
    scientificName: 'Epinephelus spp.',
    aliases: ['石斑'],
    category: FishCategory.saltwaterLure,
    rarity: FishRarity.legendary,
    habitat: '热带海域礁石区',
    behavior: '肉食性，伏击型',
    fishingMethod: '活饵、大型软饵',
    description: '品种繁多，价值高',
    iconEmoji: '🐟',
    ),
    const FishSpecies(
    id: 'f039',
    standardName: '海鳗',
    scientificName: 'Muraenesox cinereus',
    aliases: ['虎鳗', '灰狼牙鳗'],
    category: FishCategory.saltwaterLure,
    rarity: FishRarity.legendary,
    habitat: '沿海海域、礁石区',
    behavior: '肉食性，夜行性',
    fishingMethod: '活饵、软饵',
    description: '凶猛的肉食鱼',
    iconEmoji: '🐍',
    ),
    const FishSpecies(
    id: 'f040',
    standardName: 'GT(牛港鲹)',
    scientificName: 'Caranx hippos',
    aliases: ['杰克鱼', '海令'],
    category: FishCategory.saltwaterLure,
    rarity: FishRarity.rare,
    habitat: '热带海域',
    behavior: '肉食性，游泳速度快',
    fishingMethod: '波扒、铅笔、米诺',
    description: '路亚钓友最爱的海鱼之一',
    iconEmoji: '🐟',
    ),
    const FishSpecies(
    id: 'f041',
    standardName: '海红钻',
    scientificName: 'Lutjanus sebae',
    aliases: ['红钻鱼'],
    category: FishCategory.saltwaterLure,
    rarity: FishRarity.legendary,
    habitat: '热带海域礁石区',
    behavior: '肉食性',
    fishingMethod: '活饵、软饵',
    description: '色彩鲜艳的海鱼',
    iconEmoji: '🐟',
    ),
    const FishSpecies(
    id: 'f042',
    standardName: '黄鳍鲷',
    scientificName: 'Acanthopagrus latus',
    aliases: ['黄脚立'],
    category: FishCategory.saltwaterLure,
    rarity: FishRarity.rare,
    habitat: '沿海海域、河口',
    behavior: '杂食性',
    fishingMethod: '软饵、活饵',
    description: '鳍条呈黄色',
    iconEmoji: '🐟',
    ),
    const FishSpecies(
    id: 'f043',
    standardName: '平鲷',
    scientificName: 'Rhabdosargus sarba',
    aliases: ['鞭鱼'],
    category: FishCategory.saltwaterLure,
    rarity: FishRarity.rare,
    habitat: '沿海海域',
    behavior: '杂食性',
    fishingMethod: '软饵、活饵',
    description: '体型侧扁',
    iconEmoji: '🐟',
    ),
    const FishSpecies(
    id: 'f044',
    standardName: '黑毛',
    scientificName: 'Girella leonina',
    aliases: ['桑氏唇鱼'],
    category: FishCategory.saltwaterLure,
    rarity: FishRarity.legendary,
    habitat: '礁石海域',
    behavior: '草食性',
    fishingMethod: '素饵',
    description: '礁石区常见鱼',
    iconEmoji: '🐟',
    ),
    const FishSpecies(
    id: 'f045',
    standardName: '鹤鱵',
    scientificName: 'Tylosurus crocodilus',
    aliases: ['针鱼', '颌针鱼'],
    category: FishCategory.saltwaterLure,
    rarity: FishRarity.rare,
    habitat: '沿海海域',
    behavior: '肉食性，游泳速度快',
    fishingMethod: '小型软饵、飞蝇',
    description: '体型细长如针',
    iconEmoji: '🐟',
    ),
    const FishSpecies(
    id: 'f046',
    standardName: '烟仔',
    scientificName: 'Pompanax vacuus',
    aliases: ['蓝鳍鲹'],
    category: FishCategory.saltwaterLure,
    rarity: FishRarity.uncommon,
    habitat: '沿海海域',
    behavior: '群居肉食性',
    fishingMethod: '小型亮片、软饵',
    description: '小体型鲹科鱼',
    iconEmoji: '🐟',
    ),
    const FishSpecies(
    id: 'f047',
    standardName: '金目鲈',
    scientificName: 'Priacanthus macracanthus',
    aliases: ['大眼鲈'],
    category: FishCategory.saltwaterLure,
    rarity: FishRarity.rare,
    habitat: '深海海域',
    behavior: '肉食性',
    fishingMethod: '活饵、软饵',
    description: '眼睛呈金色',
    iconEmoji: '🐟',
    ),
    const FishSpecies(
    id: 'f048',
    standardName: '石首鱼',
    scientificName: 'Sciaenops ocellatus',
    aliases: ['黄鱼'],
    category: FishCategory.saltwaterLure,
    rarity: FishRarity.rare,
    habitat: '沿海海域',
    behavior: '底栖肉食性',
    fishingMethod: '软饵、活饵',
    description: '头部有石状突起',
    iconEmoji: '🐟',
    ),
    const FishSpecies(
    id: 'f049',
    standardName: '海鳜',
    scientificName: 'Variola louti',
    aliases: ['塔西提石斑'],
    category: FishCategory.saltwaterLure,
    rarity: FishRarity.mythical,
    habitat: '热带海域礁石',
    behavior: '肉食性',
    fishingMethod: '活饵、大型软饵',
    description: '色彩艳丽的大型石斑',
    iconEmoji: '🐟',
    ),
    const FishSpecies(
    id: 'f050',
    standardName: '蓝鳍金枪鱼',
    scientificName: 'Thunnus thynnus',
    aliases: [],
    category: FishCategory.saltwaterLure,
    rarity: FishRarity.mythical,
    habitat: '深海海域',
    behavior: '肉食性，洄游',
    fishingMethod: '大型拟饵',
    description: '顶级海钓鱼种',
    iconEmoji: '🐟',
    ),
  ];
}
