import 'dart:convert';
import 'dart:typed_data';
import '../models/fish_catch.dart';
import '../utils/unit_converter.dart';

/// 文本导出器 - 渔获报告生成
///
/// 将渔获记录转换为可打印的文本报告格式（UTF-8 编码）：
/// - 报告头部：标题、统计周期
/// - 概要统计：总渔获数、放流数、保留数
/// - 品种分布：各物种的钓获数量统计
/// - 渔获明细：每条记录的完整信息列表
/// - 报告尾部：生成工具版本信息
///
/// 输出为 UTF-8 编码的字节数据，可直接用于 PDF 打印或文件保存。

class TextExporter {
  static Future<Uint8List> exportFishCatchesText({
    required List<FishCatch> catches,
    DateTime? startDate,
    DateTime? endDate,
    required String appVersion,
    String lengthUnit = 'cm',
    String weightUnit = 'kg',
    String temperatureUnit = 'C',
  }) async {
    final buffer = StringBuffer();

    buffer.writeln('渔获记录报告');
    buffer.writeln('================');

    if (startDate != null || endDate != null) {
      buffer.write('统计周期: ');
      buffer.write(startDate?.toIso8601String() ?? '开始');
      buffer.write(' - ');
      buffer.writeln(endDate?.toIso8601String() ?? '现在');
    }

    buffer.writeln('');
    buffer.writeln('概要统计');
    buffer.writeln('--------');
    buffer.writeln('总渔获数: ${catches.length}');
    buffer.writeln(
      '放流数量: ${catches.where((f) => f.fate == FishFateType.release).length}',
    );
    buffer.writeln(
      '保留数量: ${catches.where((f) => f.fate == FishFateType.keep).length}',
    );

    final speciesCount = <String, int>{};
    for (final fish in catches) {
      speciesCount[fish.species] = (speciesCount[fish.species] ?? 0) + 1;
    }

    buffer.writeln('');
    buffer.writeln('品种分布');
    buffer.writeln('--------');
    for (final entry in speciesCount.entries) {
      buffer.writeln('${entry.key}: ${entry.value}尾');
    }

    buffer.writeln('');
    buffer.writeln('渔获明细');
    buffer.writeln('--------');
    for (final fish in catches) {
      final displayLength = fish.lengthUnit != lengthUnit
          ? UnitConverter.convertLength(fish.length, fish.lengthUnit, lengthUnit)
          : fish.length;
      final displayLengthSymbol = UnitConverter.getLengthSymbol(lengthUnit);
      String displayWeightSymbol = UnitConverter.getWeightSymbol(weightUnit);
      double? displayWeight;
      if (fish.weight != null) {
        displayWeight = fish.weightUnit != weightUnit
            ? UnitConverter.convertWeight(fish.weight!, fish.weightUnit, weightUnit)
            : fish.weight;
      }
      buffer.writeln(
        '${fish.catchTime.toIso8601String().substring(0, 10)} | '
        '${fish.species} | '
        '${displayLength.toStringAsFixed(2)}$displayLengthSymbol | '
        '${displayWeight?.toStringAsFixed(2) ?? '-'}$displayWeightSymbol | '
        '${fish.fate.label}',
      );
    }

    buffer.writeln('');
    buffer.writeln('--------');
    buffer.writeln('Generated by Lurebox v$appVersion');

    return Uint8List.fromList(utf8.encode(buffer.toString()));
  }
}
