import 'dart:convert';
import 'package:flutter_test/flutter_test.dart';
import 'package:lurebox/core/models/fish_catch.dart';
import 'package:lurebox/core/services/text_exporter.dart';

void main() {
  group('TextExporter', () {
    group('exportFishCatchesText', () {
      test('exports empty list with basic stats', () async {
        final result = await TextExporter.exportFishCatchesText(
          catches: [],
          appVersion: '1.0.0',
        );

        expect(result, isNotEmpty);

        final text = utf8.decode(result);
        expect(text, contains('渔获记录报告'));
        expect(text, contains('总渔获数: 0'));
        expect(text, contains('放流数量: 0'));
        expect(text, contains('保留数量: 0'));
        expect(text, contains('Generated by Lurebox v1.0.0'));
      });

      test('exports basic fish catch data', () async {
        final catches = [
          FishCatch(
            id: 1,
            imagePath: '/test/fish.jpg',
            species: '鳜鱼',
            length: 35.5,
            weight: 1.2,
            fate: FishFateType.release,
            catchTime: DateTime(2024, 6, 15, 10, 30),
            createdAt: DateTime(2024, 6, 15),
            updatedAt: DateTime(2024, 6, 15),
          ),
        ];

        final result = await TextExporter.exportFishCatchesText(
          catches: catches,
          appVersion: '1.0.0',
        );

        final text = utf8.decode(result);
        expect(text, contains('总渔获数: 1'));
        expect(text, contains('放流数量: 1'));
        expect(text, contains('保留数量: 0'));
        expect(text, contains('鳜鱼'));
        expect(text, contains('35.5cm'));
        expect(text, contains('1.2kg'));
      });

      test('includes date range when provided', () async {
        final catches = [
          FishCatch(
            id: 1,
            imagePath: '/test/fish.jpg',
            species: '鳜鱼',
            length: 35.0,
            fate: FishFateType.release,
            catchTime: DateTime(2024, 6, 15),
            createdAt: DateTime(2024, 6, 15),
            updatedAt: DateTime(2024, 6, 15),
          ),
        ];

        final result = await TextExporter.exportFishCatchesText(
          catches: catches,
          startDate: DateTime(2024, 1, 1),
          endDate: DateTime(2024, 12, 31),
          appVersion: '1.0.0',
        );

        final text = utf8.decode(result);
        expect(text, contains('统计周期'));
        expect(text, contains('2024-01-01'));
        expect(text, contains('2024-12-31'));
      });

      test('shows only start date when end date is null', () async {
        final catches = [
          FishCatch(
            id: 1,
            imagePath: '/test/fish.jpg',
            species: 'Test',
            length: 30.0,
            fate: FishFateType.release,
            catchTime: DateTime(2024, 6, 15),
            createdAt: DateTime(2024, 6, 15),
            updatedAt: DateTime(2024, 6, 15),
          ),
        ];

        final result = await TextExporter.exportFishCatchesText(
          catches: catches,
          startDate: DateTime(2024, 1, 1),
          appVersion: '1.0.0',
        );

        final text = utf8.decode(result);
        expect(text, contains('2024-01-01'));
        expect(text, contains('现在')); // When only startDate is set, shows "现在" for end
      });

      test('shows only end date when start date is null', () async {
        final catches = [
          FishCatch(
            id: 1,
            imagePath: '/test/fish.jpg',
            species: 'Test',
            length: 30.0,
            fate: FishFateType.release,
            catchTime: DateTime(2024, 6, 15),
            createdAt: DateTime(2024, 6, 15),
            updatedAt: DateTime(2024, 6, 15),
          ),
        ];

        final result = await TextExporter.exportFishCatchesText(
          catches: catches,
          endDate: DateTime(2024, 12, 31),
          appVersion: '1.0.0',
        );

        final text = utf8.decode(result);
        expect(text, contains('2024-12-31'));
        expect(text, contains('开始')); // When only endDate is set, shows "开始"
      });

      test('calculates species distribution correctly', () async {
        final catches = [
          FishCatch(
            id: 1,
            imagePath: '/1.jpg',
            species: '鳜鱼',
            length: 30.0,
            fate: FishFateType.release,
            catchTime: DateTime(2024, 6, 15),
            createdAt: DateTime(2024, 6, 15),
            updatedAt: DateTime(2024, 6, 15),
          ),
          FishCatch(
            id: 2,
            imagePath: '/2.jpg',
            species: '鳜鱼',
            length: 35.0,
            fate: FishFateType.keep,
            catchTime: DateTime(2024, 6, 16),
            createdAt: DateTime(2024, 6, 16),
            updatedAt: DateTime(2024, 6, 16),
          ),
          FishCatch(
            id: 3,
            imagePath: '/3.jpg',
            species: '黑鱼',
            length: 40.0,
            fate: FishFateType.release,
            catchTime: DateTime(2024, 6, 17),
            createdAt: DateTime(2024, 6, 17),
            updatedAt: DateTime(2024, 6, 17),
          ),
        ];

        final result = await TextExporter.exportFishCatchesText(
          catches: catches,
          appVersion: '1.0.0',
        );

        final text = utf8.decode(result);
        expect(text, contains('鳜鱼: 2尾'));
        expect(text, contains('黑鱼: 1尾'));
      });

      test('handles null weight gracefully', () async {
        final catches = [
          FishCatch(
            id: 1,
            imagePath: '/test/fish.jpg',
            species: 'Test',
            length: 35.0,
            weight: null, // null weight
            fate: FishFateType.release,
            catchTime: DateTime(2024, 6, 15),
            createdAt: DateTime(2024, 6, 15),
            updatedAt: DateTime(2024, 6, 15),
          ),
        ];

        final result = await TextExporter.exportFishCatchesText(
          catches: catches,
          appVersion: '1.0.0',
        );

        final text = utf8.decode(result);
        expect(text, contains('-kg')); // null weight shown as dash
      });

      test('exports multiple catches with details', () async {
        final catches = [
          FishCatch(
            id: 1,
            imagePath: '/1.jpg',
            species: '鳜鱼',
            length: 35.0,
            weight: 1.5,
            fate: FishFateType.release,
            catchTime: DateTime(2024, 6, 15),
            createdAt: DateTime(2024, 6, 15),
            updatedAt: DateTime(2024, 6, 15),
          ),
          FishCatch(
            id: 2,
            imagePath: '/2.jpg',
            species: '黑鱼',
            length: 40.0,
            weight: 2.0,
            fate: FishFateType.keep,
            catchTime: DateTime(2024, 6, 16),
            createdAt: DateTime(2024, 6, 16),
            updatedAt: DateTime(2024, 6, 16),
          ),
        ];

        final result = await TextExporter.exportFishCatchesText(
          catches: catches,
          appVersion: '1.0.0',
        );

        final text = utf8.decode(result);
        expect(text, contains('渔获明细'));
        expect(text, contains('2024-06-15'));
        expect(text, contains('2024-06-16'));
        expect(text, contains('鳜鱼'));
        expect(text, contains('黑鱼'));
        expect(text, contains('放流'));
        expect(text, contains('保留'));
      });

      test('outputs UTF-8 encoded bytes', () async {
        final catches = [
          FishCatch(
            id: 1,
            imagePath: '/test/fish.jpg',
            species: 'TestFish',
            length: 35.0,
            fate: FishFateType.release,
            catchTime: DateTime(2024, 6, 15),
            createdAt: DateTime(2024, 6, 15),
            updatedAt: DateTime(2024, 6, 15),
          ),
        ];

        final result = await TextExporter.exportFishCatchesText(
          catches: catches,
          appVersion: '1.0.0',
        );

        // Verify UTF-8 encoding by decoding back
        final text = utf8.decode(result);
        expect(text.contains('TestFish'), isTrue);
        expect(text.contains('35.0cm'), isTrue);
        // UTF-8 encoding works - other tests with Chinese characters verify the encoding
      });

      test('release rate calculation is correct', () async {
        final catches = [
          FishCatch(
            id: 1,
            imagePath: '/1.jpg',
            species: 'A',
            length: 30.0,
            fate: FishFateType.release,
            catchTime: DateTime(2024, 6, 15),
            createdAt: DateTime(2024, 6, 15),
            updatedAt: DateTime(2024, 6, 15),
          ),
          FishCatch(
            id: 2,
            imagePath: '/2.jpg',
            species: 'B',
            length: 30.0,
            fate: FishFateType.release,
            catchTime: DateTime(2024, 6, 15),
            createdAt: DateTime(2024, 6, 15),
            updatedAt: DateTime(2024, 6, 15),
          ),
          FishCatch(
            id: 3,
            imagePath: '/3.jpg',
            species: 'C',
            length: 30.0,
            fate: FishFateType.keep,
            catchTime: DateTime(2024, 6, 15),
            createdAt: DateTime(2024, 6, 15),
            updatedAt: DateTime(2024, 6, 15),
          ),
        ];

        final result = await TextExporter.exportFishCatchesText(
          catches: catches,
          appVersion: '1.0.0',
        );

        final text = utf8.decode(result);
        expect(text, contains('总渔获数: 3'));
        expect(text, contains('放流数量: 2'));
        expect(text, contains('保留数量: 1'));
      });

      test('handles large number of catches', () async {
        final catches = List.generate(
          100,
          (i) => FishCatch(
            id: i,
            imagePath: '/$i.jpg',
            species: 'Species${i % 5}',
            length: 30.0 + i,
            fate: i % 2 == 0 ? FishFateType.release : FishFateType.keep,
            catchTime: DateTime(2024, 6, 15),
            createdAt: DateTime(2024, 6, 15),
            updatedAt: DateTime(2024, 6, 15),
          ),
        );

        final result = await TextExporter.exportFishCatchesText(
          catches: catches,
          appVersion: '1.0.0',
        );

        final text = utf8.decode(result);
        // Verify basic structure - UTF-8 encoding is working
        expect(text.startsWith('渔获记录报告'), isTrue);
        expect(text.contains('Generated by Lurebox v1.0.0'), isTrue);
        // Verify stats are included (ASCII check to avoid terminal display issues)
        expect(text.contains('总渔获数: 100'), isTrue);
        expect(text.contains('Species0'), isTrue);
      });
    });
  });
}
