import '../../core/models/fish_species.dart';

/// 鱼类图鉴数据
///
/// 包含100+种预定义的鱼类物种数据
class FishGuideData {
  FishGuideData._();

  /// 全部鱼类物种列表
  static List<FishSpecies> get allSpecies => [
        ...freshwaterLureSpecies,
        ...freshwaterGeneralSpecies,
      ];

  /// 淡水路亚鱼种 (f001-f050)
  static List<FishSpecies> get freshwaterLureSpecies => [
        const FishSpecies(
          id: 'f001',
          standardName: '鳜鱼',
          scientificName: 'Siniperca chuatsi',
          aliases: ['桂鱼', '桂花鱼', '鳜花', '翘嘴鳜'],
          category: FishCategory.freshwaterLure,
          rarity: FishRarity.rare,
          habitat: '江河、湖泊、水库',
          behavior: '肉食性鱼类，伏击型捕食',
          fishingMethod: '软饵、亮片、米诺',
          description: '典型肉食性淡水鱼，体侧有黑色斑点',
          iconEmoji: '🐟',
        ),
        const FishSpecies(
          id: 'f002',
          standardName: '大口黑鲈',
          scientificName: 'Micropterus salmoides',
          aliases: ['加拿大鳜鱼', '黑鲈'],
          category: FishCategory.freshwaterLure,
          rarity: FishRarity.uncommon,
          habitat: '湖泊、水库、河流',
          behavior: '肉食性，攻击性强',
          fishingMethod: '软饵、crankbait、spinnerbait',
          description: '原产北美，入侵我国的外来物种',
          iconEmoji: '🐠',
        ),
        const FishSpecies(
          id: 'f003',
          standardName: '河鲈',
          scientificName: 'Perca fluviatilis',
          aliases: ['五道黑'],
          category: FishCategory.freshwaterLure,
          rarity: FishRarity.rare,
          habitat: '江河、湖泊',
          behavior: '群居肉食性鱼类',
          fishingMethod: '亮片、小型软饵',
          description: '体侧有五道黑色横纹',
          iconEmoji: '🐟',
        ),
        const FishSpecies(
          id: 'f004',
          standardName: '乌鳢',
          scientificName: 'Channa argus',
          aliases: ['黑鱼', '财鱼', '生鱼', '斑鳢'],
          category: FishCategory.freshwaterLure,
          rarity: FishRarity.common,
          habitat: '池塘、湖泊、河流',
          behavior: '肉食性，伏击型，会护幼',
          fishingMethod: '软饵、面包虫',
          description: '适应能力强，能在缺氧环境中生存',
          iconEmoji: '🐍',
        ),
        const FishSpecies(
          id: 'f005',
          standardName: '斑鳢',
          scientificName: 'Channa maculata',
          aliases: ['斑鱼', '月鳢'],
          category: FishCategory.freshwaterLure,
          rarity: FishRarity.uncommon,
          habitat: '南方淡水流域',
          behavior: '肉食性，昼伏夜出',
          fishingMethod: '软饵、活饵',
          description: '与乌鳢相似，但花纹不同',
          iconEmoji: '🐟',
        ),
        const FishSpecies(
          id: 'f006',
          standardName: '翘嘴红鲌',
          scientificName: 'Culter alburnus',
          aliases: ['翘嘴', '大白鱼'],
          category: FishCategory.freshwaterLure,
          rarity: FishRarity.uncommon,
          habitat: '江河、湖泊',
          behavior: '肉食性，掠食游速快',
          fishingMethod: '亮片、米诺、波扒',
          description: '体型修长，嘴型上翘',
          iconEmoji: '🐟',
        ),
        const FishSpecies(
          id: 'f007',
          standardName: '蒙古红鲌',
          scientificName: 'Culter mongolicus',
          aliases: ['红梢', '小白鱼'],
          category: FishCategory.freshwaterLure,
          rarity: FishRarity.uncommon,
          habitat: '江河、湖泊',
          behavior: '群居小体型肉食性',
          fishingMethod: '小型亮片、软饵',
          description: '体型较小的红尾掠食鱼',
          iconEmoji: '🐟',
        ),
        const FishSpecies(
          id: 'f008',
          standardName: '黄颡鱼',
          scientificName: 'Pelteobagrus fulvidraco',
          aliases: ['黄辣丁', '昂刺鱼', '黄骨鱼'],
          category: FishCategory.freshwaterLure,
          rarity: FishRarity.uncommon,
          habitat: '江河、湖泊、池塘',
          behavior: '夜行性，底栖肉食性',
          fishingMethod: '软饵、虫饵',
          description: '体色金黄，有毒刺',
          iconEmoji: '🐟',
        ),
        const FishSpecies(
          id: 'f009',
          standardName: '瓦氏黄颡鱼',
          scientificName: 'Pelteobagrus vachelli',
          aliases: ['江黄颡'],
          category: FishCategory.freshwaterLure,
          rarity: FishRarity.rare,
          habitat: '长江流域',
          behavior: '底栖肉食性',
          fishingMethod: '软饵、虫饵',
          description: '体型比黄颡鱼大',
          iconEmoji: '🐟',
        ),
        const FishSpecies(
          id: 'f010',
          standardName: '斑点叉尾鮰',
          scientificName: 'Ictalurus punctatus',
          aliases: ['沟鲇', '钳鱼'],
          category: FishCategory.freshwaterLure,
          rarity: FishRarity.rare,
          habitat: '江河、湖泊、水库',
          behavior: '杂食性，适应性强',
          fishingMethod: '软饵、虫饵',
          description: '原产北美，我国引进养殖',
          iconEmoji: '🐟',
        ),
        const FishSpecies(
          id: 'f011',
          standardName: '革胡子鲇',
          scientificName: 'Clarias gariepinus',
          aliases: ['埃及塘鲺'],
          category: FishCategory.freshwaterLure,
          rarity: FishRarity.uncommon,
          habitat: '池塘、稻田',
          behavior: '杂食性，适应力极强',
          fishingMethod: '软饵、活饵',
          description: '外来物种，繁殖能力强',
          iconEmoji: '🐟',
        ),
        const FishSpecies(
          id: 'f012',
          standardName: '南方大口鲇',
          scientificName: 'Silurus meridionalis',
          aliases: ['土鲇', '大河鲇'],
          category: FishCategory.freshwaterLure,
          rarity: FishRarity.rare,
          habitat: '长江以南淡水流域',
          behavior: '肉食性，夜行性',
          fishingMethod: '大型软饵、活饵',
          description: '体型大，口裂大',
          iconEmoji: '🐟',
        ),
        const FishSpecies(
          id: 'f013',
          standardName: '北方大口鲇',
          scientificName: 'Silurus asotus',
          aliases: ['东北大口鲇'],
          category: FishCategory.freshwaterLure,
          rarity: FishRarity.rare,
          habitat: '东北地区淡水',
          behavior: '肉食性，夜行性',
          fishingMethod: '大型软饵、活饵',
          description: '北方特有大型鲇鱼',
          iconEmoji: '🐟',
        ),
        const FishSpecies(
          id: 'f014',
          standardName: '鲇鱼',
          scientificName: 'Silurus asotus',
          aliases: ['鲶鱼', '土鲇'],
          category: FishCategory.freshwaterLure,
          rarity: FishRarity.uncommon,
          habitat: '江河、湖泊、池塘',
          behavior: '肉食性，夜行性',
          fishingMethod: '软饵、虫饵',
          description: '体表无鳞，适应力强',
          iconEmoji: '🐱',
        ),
        const FishSpecies(
          id: 'f015',
          standardName: '马口鱼',
          scientificName: 'Opsariichthys bidens',
          aliases: ['马口', '宽鳍'],
          category: FishCategory.freshwaterLure,
          rarity: FishRarity.common,
          habitat: '清澈溪流',
          behavior: '群居，小型肉食性',
          fishingMethod: '小型亮片、飞蝇',
          description: '雄鱼婚姻色鲜艳',
          iconEmoji: '🐟',
        ),
        const FishSpecies(
          id: 'f016',
          standardName: '宽鳍鱲',
          scientificName: 'Zacco temminckii',
          aliases: ['桃花鱼', '红猫鱼'],
          category: FishCategory.freshwaterLure,
          rarity: FishRarity.uncommon,
          habitat: '山涧溪流',
          behavior: '群居，杂食性',
          fishingMethod: '小型亮片、飞蝇',
          description: '春季繁殖期体色艳丽',
          iconEmoji: '🐟',
        ),
        const FishSpecies(
          id: 'f017',
          standardName: '餐条',
          scientificName: 'Hemiculter leucisculus',
          aliases: ['白条', '餐子'],
          category: FishCategory.freshwaterLure,
          rarity: FishRarity.common,
          habitat: '湖泊、河流',
          behavior: '群居，杂食性',
          fishingMethod: '小型亮片、飞蝇',
          description: '常见小型鱼，数量多',
          iconEmoji: '🐟',
        ),
        const FishSpecies(
          id: 'f018',
          standardName: '红眼金线鱼',
          scientificName: 'Rhodeus sericeus',
          aliases: ['红眼', '金线'],
          category: FishCategory.freshwaterLure,
          rarity: FishRarity.rare,
          habitat: '静水或缓流',
          behavior: '杂食性，繁殖方式特殊',
          fishingMethod: '小型软饵',
          description: '眼睛呈红色',
          iconEmoji: '🐟',
        ),
        const FishSpecies(
          id: 'f019',
          standardName: '鳊鱼',
          scientificName: 'Parabramis pekinensis',
          aliases: ['长春鳊', '草鳊'],
          category: FishCategory.freshwaterLure,
          rarity: FishRarity.uncommon,
          habitat: '江河、湖泊',
          behavior: '草食性',
          fishingMethod: '素饵、面包',
          description: '体型侧扁，草食性',
          iconEmoji: '🐟',
        ),
        const FishSpecies(
          id: 'f020',
          standardName: '中华细鲫',
          scientificName: 'Aphyocypris chinensis',
          aliases: ['草鱼苗', '小白鲢'],
          category: FishCategory.freshwaterLure,
          rarity: FishRarity.uncommon,
          habitat: '南方淡水',
          behavior: '杂食性',
          fishingMethod: '小型软饵',
          description: '小型淡水鱼',
          iconEmoji: '🐟',
        ),
        const FishSpecies(
          id: 'f021',
          standardName: '蓝鳍鲫',
          scientificName: 'Cyprinus carpio',
          aliases: ['小金线'],
          category: FishCategory.freshwaterLure,
          rarity: FishRarity.uncommon,
          habitat: '淡水流域',
          behavior: '杂食性',
          fishingMethod: '软饵、谷物饵',
          description: '鳍条带蓝色',
          iconEmoji: '🐟',
        ),
        const FishSpecies(
          id: 'f022',
          standardName: '泥鳅',
          scientificName: 'Misgurnus anguillicaudatus',
          aliases: ['泥鳅鱼'],
          category: FishCategory.freshwaterLure,
          rarity: FishRarity.common,
          habitat: '池塘、稻田、河流',
          behavior: '杂食性，底栖',
          fishingMethod: '软饵、虫饵',
          description: '耐低氧，适应性强',
          iconEmoji: '🐍',
        ),
        const FishSpecies(
          id: 'f023',
          standardName: '黄鳝',
          scientificName: 'Monopterus albus',
          aliases: ['鳝鱼', '长鱼'],
          category: FishCategory.freshwaterLure,
          rarity: FishRarity.uncommon,
          habitat: '稻田、池塘、河流',
          behavior: '肉食性，夜行性',
          fishingMethod: '软饵、蚯蚓',
          description: '体型细长，无鳞',
          iconEmoji: '🐍',
        ),
        const FishSpecies(
          id: 'f024',
          standardName: '鳗鱼',
          scientificName: 'Anguilla japonica',
          aliases: ['河鳗', '白鳝'],
          category: FishCategory.freshwaterLure,
          rarity: FishRarity.rare,
          habitat: '江河入海口',
          behavior: '降海繁殖，肉食性',
          fishingMethod: '活饵、软饵',
          description: '洄游性鱼类',
          iconEmoji: '🐍',
        ),
        const FishSpecies(
          id: 'f025',
          standardName: '刀鱼',
          scientificName: 'Coilia nasus',
          aliases: ['凤尾鱼', '刀鲚'],
          category: FishCategory.freshwaterLure,
          rarity: FishRarity.rare,
          habitat: '长江中下游',
          behavior: '肉食性小型鱼',
          fishingMethod: '小型软饵',
          description: '体型侧扁如刀',
          iconEmoji: '🐟',
        ),
        const FishSpecies(
          id: 'f026',
          standardName: '河鲀',
          scientificName: 'Takifugu spp.',
          aliases: ['河豚', '气鼓鱼'],
          category: FishCategory.freshwaterLure,
          rarity: FishRarity.legendary,
          habitat: '江河入海口',
          behavior: '肉食性，受惊充气',
          fishingMethod: '软饵、活饵',
          description: '体内有河豚毒素',
          iconEmoji: '🐡',
        ),
        const FishSpecies(
          id: 'f027',
          standardName: '中华鲂',
          scientificName: 'Megalobrama amblycephala',
          aliases: ['武昌鱼', '团头鲂'],
          category: FishCategory.freshwaterLure,
          rarity: FishRarity.uncommon,
          habitat: '长江中下游',
          behavior: '草食性',
          fishingMethod: '素饵、蔬菜',
          description: '著名淡水养殖鱼',
          iconEmoji: '🐟',
        ),
        const FishSpecies(
          id: 'f028',
          standardName: '三角鲂',
          scientificName: 'Megalobrama terminalis',
          aliases: ['三角鳊'],
          category: FishCategory.freshwaterLure,
          rarity: FishRarity.uncommon,
          habitat: '江河、湖泊',
          behavior: '草食性',
          fishingMethod: '素饵',
          description: '体型呈三角形',
          iconEmoji: '🐟',
        ),
        const FishSpecies(
          id: 'f029',
          standardName: '虹鳟',
          scientificName: 'Oncorhynchus mykiss',
          aliases: ['虹鳟鱼'],
          category: FishCategory.freshwaterLure,
          rarity: FishRarity.legendary,
          habitat: '冷水溪流',
          behavior: '肉食性，喜冷水',
          fishingMethod: '飞蝇、亮片',
          description: '侧线有彩虹色斑纹',
          iconEmoji: '🐟',
        ),
        const FishSpecies(
          id: 'f030',
          standardName: '金鳟',
          scientificName: 'Oncorhynchus mykiss',
          aliases: [],
          category: FishCategory.freshwaterLure,
          rarity: FishRarity.legendary,
          habitat: '冷水溪流',
          behavior: '肉食性',
          fishingMethod: '飞蝇、亮片',
          description: '虹鳟的金色变异种',
          iconEmoji: '🐟',
        ),
        const FishSpecies(
          id: 'f031',
          standardName: '胭脂鱼',
          scientificName: 'Myxocyprinus asiaticus',
          aliases: ['火烧鳊', '一帆风顺'],
          category: FishCategory.freshwaterLure,
          rarity: FishRarity.legendary,
          habitat: '长江上游',
          behavior: '杂食性',
          fishingMethod: '软饵',
          description: '中国特有淡水鱼',
          iconEmoji: '🐟',
        ),
        const FishSpecies(
          id: 'f032',
          standardName: '鸭嘴鲇',
          scientificName: 'Polyodon spathula',
          aliases: ['鸭嘴鱼', '匙吻鲇'],
          category: FishCategory.freshwaterLure,
          rarity: FishRarity.legendary,
          habitat: '北美淡水',
          behavior: '滤食性',
          fishingMethod: '软饵',
          description: '原产北美，嘴呈鸭嘴状',
          iconEmoji: '🐟',
        ),
        const FishSpecies(
          id: 'f033',
          standardName: '中华鲟',
          scientificName: 'Acipenser sinensis',
          aliases: ['鳇鱼', '腊子'],
          category: FishCategory.freshwaterLure,
          rarity: FishRarity.mythical,
          habitat: '长江',
          behavior: '肉食性，洄游性',
          fishingMethod: '大型活饵',
          description: '国家一级保护动物',
          iconEmoji: '🦈',
        ),
        const FishSpecies(
          id: 'f034',
          standardName: '白鲟',
          scientificName: 'Psephurus gladius',
          aliases: ['象鱼', '棍子鱼'],
          category: FishCategory.freshwaterLure,
          rarity: FishRarity.mythical,
          habitat: '长江',
          behavior: '肉食性',
          fishingMethod: '大型活饵',
          description: '已功能性灭绝的巨型淡水鱼',
          iconEmoji: '🦈',
        ),
        const FishSpecies(
          id: 'f035',
          standardName: '海鲈',
          scientificName: 'Lateolabrax japonicus',
          aliases: ['七星鲈', '花鲈'],
          category: FishCategory.freshwaterLure,
          rarity: FishRarity.uncommon,
          habitat: '沿海海域、河口',
          behavior: '肉食性，洄游',
          fishingMethod: '软饵、亮片、米诺',
          description: '可入淡水的海产鱼',
          iconEmoji: '🐟',
        ),
        const FishSpecies(
          id: 'f036',
          standardName: '黑鲷',
          scientificName: 'Acanthopagrus schlegelii',
          aliases: ['海鲋', '黑棘鲷'],
          category: FishCategory.freshwaterLure,
          rarity: FishRarity.rare,
          habitat: '沿海海域、礁石区',
          behavior: '杂食性，地域性强',
          fishingMethod: '软饵、活饵',
          description: '高级海钓鱼种',
          iconEmoji: '🐟',
        ),
        const FishSpecies(
          id: 'f037',
          standardName: '真鲷',
          scientificName: 'Pagrus major',
          aliases: ['加计鱼', '红鲷'],
          category: FishCategory.freshwaterLure,
          rarity: FishRarity.legendary,
          habitat: '沿海海域',
          behavior: '杂食性',
          fishingMethod: '软饵、活饵',
          description: '海钓中的珍贵鱼种',
          iconEmoji: '🐟',
        ),
        const FishSpecies(
          id: 'f038',
          standardName: '石斑鱼',
          scientificName: 'Epinephelus spp.',
          aliases: ['石斑'],
          category: FishCategory.freshwaterLure,
          rarity: FishRarity.legendary,
          habitat: '热带海域礁石区',
          behavior: '肉食性，伏击型',
          fishingMethod: '活饵、大型软饵',
          description: '品种繁多，价值高',
          iconEmoji: '🐟',
        ),
        const FishSpecies(
          id: 'f039',
          standardName: '海鳗',
          scientificName: 'Muraenesox cinereus',
          aliases: ['虎鳗', '灰狼牙鳗'],
          category: FishCategory.freshwaterLure,
          rarity: FishRarity.legendary,
          habitat: '沿海海域、礁石区',
          behavior: '肉食性，夜行性',
          fishingMethod: '活饵、软饵',
          description: '凶猛的肉食鱼',
          iconEmoji: '🐍',
        ),
        const FishSpecies(
          id: 'f040',
          standardName: 'GT(牛港鲹)',
          scientificName: 'Caranx hippos',
          aliases: ['杰克鱼', '海令'],
          category: FishCategory.freshwaterLure,
          rarity: FishRarity.rare,
          habitat: '热带海域',
          behavior: '肉食性，游泳速度快',
          fishingMethod: '波扒、铅笔、米诺',
          description: '路亚钓友最爱的海鱼之一',
          iconEmoji: '🐟',
        ),
        const FishSpecies(
          id: 'f041',
          standardName: '海红钻',
          scientificName: 'Lutjanus sebae',
          aliases: ['红钻鱼'],
          category: FishCategory.freshwaterLure,
          rarity: FishRarity.legendary,
          habitat: '热带海域礁石区',
          behavior: '肉食性',
          fishingMethod: '活饵、软饵',
          description: '色彩鲜艳的海鱼',
          iconEmoji: '🐟',
        ),
        const FishSpecies(
          id: 'f042',
          standardName: '黄鳍鲷',
          scientificName: 'Acanthopagrus latus',
          aliases: ['黄脚立'],
          category: FishCategory.freshwaterLure,
          rarity: FishRarity.rare,
          habitat: '沿海海域、河口',
          behavior: '杂食性',
          fishingMethod: '软饵、活饵',
          description: '鳍条呈黄色',
          iconEmoji: '🐟',
        ),
        const FishSpecies(
          id: 'f043',
          standardName: '平鲷',
          scientificName: 'Rhabdosargus sarba',
          aliases: ['鞭鱼'],
          category: FishCategory.freshwaterLure,
          rarity: FishRarity.rare,
          habitat: '沿海海域',
          behavior: '杂食性',
          fishingMethod: '软饵、活饵',
          description: '体型侧扁',
          iconEmoji: '🐟',
        ),
        const FishSpecies(
          id: 'f044',
          standardName: '黑毛',
          scientificName: 'Girella leonina',
          aliases: ['桑氏唇鱼'],
          category: FishCategory.freshwaterLure,
          rarity: FishRarity.legendary,
          habitat: '礁石海域',
          behavior: '草食性',
          fishingMethod: '素饵',
          description: '礁石区常见鱼',
          iconEmoji: '🐟',
        ),
        const FishSpecies(
          id: 'f045',
          standardName: '鹤鱵',
          scientificName: 'Tylosurus crocodilus',
          aliases: ['针鱼', '颌针鱼'],
          category: FishCategory.freshwaterLure,
          rarity: FishRarity.rare,
          habitat: '沿海海域',
          behavior: '肉食性，游泳速度快',
          fishingMethod: '小型软饵、飞蝇',
          description: '体型细长如针',
          iconEmoji: '🐟',
        ),
        const FishSpecies(
          id: 'f046',
          standardName: '烟仔',
          scientificName: 'Pompanax vacuus',
          aliases: ['蓝鳍鲹'],
          category: FishCategory.freshwaterLure,
          rarity: FishRarity.uncommon,
          habitat: '沿海海域',
          behavior: '群居肉食性',
          fishingMethod: '小型亮片、软饵',
          description: '小体型鲹科鱼',
          iconEmoji: '🐟',
        ),
        const FishSpecies(
          id: 'f047',
          standardName: '金目鲈',
          scientificName: 'Priacanthus macracanthus',
          aliases: ['大眼鲈'],
          category: FishCategory.freshwaterLure,
          rarity: FishRarity.rare,
          habitat: '深海海域',
          behavior: '肉食性',
          fishingMethod: '活饵、软饵',
          description: '眼睛呈金色',
          iconEmoji: '🐟',
        ),
        const FishSpecies(
          id: 'f048',
          standardName: '石首鱼',
          scientificName: 'Sciaenops ocellatus',
          aliases: ['黄鱼'],
          category: FishCategory.freshwaterLure,
          rarity: FishRarity.rare,
          habitat: '沿海海域',
          behavior: '底栖肉食性',
          fishingMethod: '软饵、活饵',
          description: '头部有石状突起',
          iconEmoji: '🐟',
        ),
        const FishSpecies(
          id: 'f049',
          standardName: '海鳜',
          scientificName: 'Variola louti',
          aliases: ['塔西提石斑'],
          category: FishCategory.freshwaterLure,
          rarity: FishRarity.mythical,
          habitat: '热带海域礁石',
          behavior: '肉食性',
          fishingMethod: '活饵、大型软饵',
          description: '色彩艳丽的大型石斑',
          iconEmoji: '🐟',
        ),
        const FishSpecies(
          id: 'f050',
          standardName: '蓝鳍金枪鱼',
          scientificName: 'Thunnus thynnus',
          aliases: [],
          category: FishCategory.freshwaterLure,
          rarity: FishRarity.mythical,
          habitat: '深海海域',
          behavior: '肉食性，洄游',
          fishingMethod: '大型拟饵',
          description: '顶级海钓鱼种',
          iconEmoji: '🐟',
        ),
      ];

  /// 淡水综合鱼种 (g001-g050)
  static List<FishSpecies> get freshwaterGeneralSpecies => [
        const FishSpecies(
          id: 'g001',
          standardName: '鲤鱼',
          scientificName: 'Cyprinus carpio',
          aliases: ['鲤拐子', '锦鲤'],
          category: FishCategory.freshwaterGeneral,
          rarity: FishRarity.common,
          habitat: '江河、湖泊、池塘',
          behavior: '杂食性，底栖',
          fishingMethod: '玉米、面饵、蚯蚓',
          description: '常见淡水鱼，品种繁多',
          iconEmoji: '🐉',
        ),
        const FishSpecies(
          id: 'g002',
          standardName: '鲫鱼',
          scientificName: 'Carassius auratus',
          aliases: ['鲫瓜子'],
          category: FishCategory.freshwaterGeneral,
          rarity: FishRarity.common,
          habitat: '江河、湖泊、池塘',
          behavior: '杂食性，适应性强',
          fishingMethod: '蚯蚓、红虫、面饵',
          description: '最常见的淡水鱼之一',
          iconEmoji: '🐟',
        ),
        const FishSpecies(
          id: 'g003',
          standardName: '草鱼',
          scientificName: 'Ctenopharyngodon idella',
          aliases: ['草鲩', '厚子鱼'],
          category: FishCategory.freshwaterGeneral,
          rarity: FishRarity.common,
          habitat: '江河、湖泊、池塘',
          behavior: '草食性',
          fishingMethod: '草饵、蔬菜、玉米',
          description: '体型大，生长快',
          iconEmoji: '🐉',
        ),
        const FishSpecies(
          id: 'g004',
          standardName: '青鱼',
          scientificName: 'Mylopharyngodon piceus',
          aliases: ['青鲩', '螺蛳青'],
          category: FishCategory.freshwaterGeneral,
          rarity: FishRarity.uncommon,
          habitat: '江河、湖泊',
          behavior: '肉食性偏杂',
          fishingMethod: '螺蛳、蚌肉、玉米',
          description: '喜食贝类',
          iconEmoji: '🐉',
        ),
        const FishSpecies(
          id: 'g005',
          standardName: '鲢鱼',
          scientificName: 'Hypophthalmichthys molitrix',
          aliases: ['白鲢', '鲢子'],
          category: FishCategory.freshwaterGeneral,
          rarity: FishRarity.common,
          habitat: '江河、湖泊、池塘',
          behavior: '滤食性，喜群居',
          fishingMethod: '面饵、酸臭饵',
          description: '性活泼，善跳跃',
          iconEmoji: '🐟',
        ),
        const FishSpecies(
          id: 'g006',
          standardName: '鳙鱼',
          scientificName: 'Hypophthalmichthys nobilis',
          aliases: ['花鲢', '胖头鱼'],
          category: FishCategory.freshwaterGeneral,
          rarity: FishRarity.common,
          habitat: '江河、湖泊',
          behavior: '滤食性',
          fishingMethod: '面饵、酸臭饵',
          description: '头部较大',
          iconEmoji: '🐟',
        ),
        const FishSpecies(
          id: 'g007',
          standardName: '鳜鱼',
          scientificName: 'Siniperca chuatsi',
          aliases: ['桂鱼'],
          category: FishCategory.freshwaterGeneral,
          rarity: FishRarity.common,
          habitat: '江河、湖泊',
          behavior: '肉食性，伏击',
          fishingMethod: '活饵、软饵',
          description: '常见淡水肉食鱼',
          iconEmoji: '🐟',
        ),
        const FishSpecies(
          id: 'g008',
          standardName: '鲇鱼',
          scientificName: 'Silurus asotus',
          aliases: ['土鲇'],
          category: FishCategory.freshwaterGeneral,
          rarity: FishRarity.common,
          habitat: '江河、池塘',
          behavior: '肉食性，夜行',
          fishingMethod: '活饵、蚯蚓',
          description: '常见底层鱼类',
          iconEmoji: '🐱',
        ),
        const FishSpecies(
          id: 'g009',
          standardName: '梭鱼',
          scientificName: 'Mugil cephalus',
          aliases: ['梭子鱼'],
          category: FishCategory.freshwaterGeneral,
          rarity: FishRarity.uncommon,
          habitat: '沿海河口',
          behavior: '杂食性',
          fishingMethod: '面饵、虫子',
          description: '可入淡水的海鱼',
          iconEmoji: '🐟',
        ),
        const FishSpecies(
          id: 'g010',
          standardName: '罗非鱼',
          scientificName: 'Tilapia spp.',
          aliases: ['非洲鲫'],
          category: FishCategory.freshwaterGeneral,
          rarity: FishRarity.uncommon,
          habitat: '南方淡水',
          behavior: '杂食性，适应性强',
          fishingMethod: '面饵、玉米',
          description: '外来物种，繁殖快',
          iconEmoji: '🐟',
        ),
        const FishSpecies(
          id: 'g011',
          standardName: '鲮鱼',
          scientificName: 'Cirrhinus molitorella',
          aliases: ['土鲮'],
          category: FishCategory.freshwaterGeneral,
          rarity: FishRarity.uncommon,
          habitat: '南方淡水',
          behavior: '杂食性，底栖',
          fishingMethod: '面饵、玉米',
          description: '华南地区常见鱼',
          iconEmoji: '🐟',
        ),
        const FishSpecies(
          id: 'g012',
          standardName: '鳜鱼',
          scientificName: 'Butis spp.',
          aliases: ['笋壳鱼'],
          category: FishCategory.freshwaterGeneral,
          rarity: FishRarity.rare,
          habitat: '南方淡水',
          behavior: '肉食性',
          fishingMethod: '活饵、软饵',
          description: '笋壳鱼的一种',
          iconEmoji: '🐟',
        ),
        const FishSpecies(
          id: 'g013',
          standardName: '溪石斑',
          scientificName: 'Roccus saxatilis',
          aliases: ['石斑鱼'],
          category: FishCategory.freshwaterGeneral,
          rarity: FishRarity.rare,
          habitat: '山涧溪流',
          behavior: '肉食性',
          fishingMethod: '虫饵、软饵',
          description: '引进的冷水鱼',
          iconEmoji: '🐟',
        ),
        const FishSpecies(
          id: 'g014',
          standardName: '红眼马口',
          scientificName: 'Opsariichthys spp.',
          aliases: ['马口鱼'],
          category: FishCategory.freshwaterGeneral,
          rarity: FishRarity.uncommon,
          habitat: '溪流',
          behavior: '肉食性',
          fishingMethod: '虫饵、飞蝇',
          description: '眼睛呈红色',
          iconEmoji: '🐟',
        ),
        const FishSpecies(
          id: 'g015',
          standardName: '柳叶鱼',
          scientificName: 'Engraulis japonicus',
          aliases: [],
          category: FishCategory.freshwaterGeneral,
          rarity: FishRarity.uncommon,
          habitat: '沿海海域',
          behavior: '杂食性',
          fishingMethod: '虫饵',
          description: '小型鱼',
          iconEmoji: '🐟',
        ),
        const FishSpecies(
          id: 'g016',
          standardName: '河鲤',
          scientificName: 'Cyprinus spp.',
          aliases: ['草鲤'],
          category: FishCategory.freshwaterGeneral,
          rarity: FishRarity.uncommon,
          habitat: '江河、湖泊',
          behavior: '杂食性',
          fishingMethod: '玉米、面饵',
          description: '野生状态的鲤鱼',
          iconEmoji: '🐉',
        ),
        const FishSpecies(
          id: 'g017',
          standardName: '青鲇',
          scientificName: null,
          aliases: ['青鱼'],
          category: FishCategory.freshwaterGeneral,
          rarity: FishRarity.uncommon,
          habitat: '江河、湖泊',
          behavior: '肉食性',
          fishingMethod: '活饵、软饵',
          description: '青色系大型鱼',
          iconEmoji: '🐉',
        ),
        const FishSpecies(
          id: 'g018',
          standardName: '银鲳',
          scientificName: 'Pampus argenteus',
          aliases: ['银鲳鱼'],
          category: FishCategory.freshwaterGeneral,
          rarity: FishRarity.uncommon,
          habitat: '沿海海域、河口',
          behavior: '杂食性',
          fishingMethod: '虫饵、软饵',
          description: '体型侧扁银白色',
          iconEmoji: '🐟',
        ),
        const FishSpecies(
          id: 'g019',
          standardName: '凤鲚',
          scientificName: 'Coilia nasus',
          aliases: ['凤尾鱼'],
          category: FishCategory.freshwaterGeneral,
          rarity: FishRarity.uncommon,
          habitat: '长江口',
          behavior: '肉食性',
          fishingMethod: '虫饵',
          description: '刀鱼的一种',
          iconEmoji: '🐟',
        ),
        const FishSpecies(
          id: 'g020',
          standardName: '斑鰶',
          scientificName: 'Konosirus punctatus',
          aliases: [],
          category: FishCategory.freshwaterGeneral,
          rarity: FishRarity.uncommon,
          habitat: '沿海海域',
          behavior: '杂食性',
          fishingMethod: '虫饵',
          description: '小型海水鱼',
          iconEmoji: '🐟',
        ),
        const FishSpecies(
          id: 'g021',
          standardName: '舌鳎',
          scientificName: 'Solea spp.',
          aliases: ['鳎沙鱼'],
          category: FishCategory.freshwaterGeneral,
          rarity: FishRarity.rare,
          habitat: '沿海海域、河口',
          behavior: '底栖肉食性',
          fishingMethod: '虫饵',
          description: '体型扁平如舌',
          iconEmoji: '🐟',
        ),
        const FishSpecies(
          id: 'g022',
          standardName: '鲟鱼',
          scientificName: 'Acipenser sinensis',
          aliases: ['中华鲟'],
          category: FishCategory.freshwaterGeneral,
          rarity: FishRarity.legendary,
          habitat: '长江',
          behavior: '肉食性',
          fishingMethod: '活饵',
          description: '国家一级保护动物',
          iconEmoji: '🦈',
        ),
        const FishSpecies(
          id: 'g023',
          standardName: '鳜鱼',
          scientificName: 'Siniperca scherzeri',
          aliases: ['多鳞鳜'],
          category: FishCategory.freshwaterGeneral,
          rarity: FishRarity.rare,
          habitat: '山涧溪流',
          behavior: '肉食性',
          fishingMethod: '活饵、软饵',
          description: '小型鳜鱼',
          iconEmoji: '🐟',
        ),
        const FishSpecies(
          id: 'g024',
          standardName: '沙塘鳢',
          scientificName: 'Odontobutis obscura',
          aliases: ['沙龟'],
          category: FishCategory.freshwaterGeneral,
          rarity: FishRarity.uncommon,
          habitat: '淡水溪流',
          behavior: '肉食性',
          fishingMethod: '虫饵',
          description: '小型淡水鱼',
          iconEmoji: '🐟',
        ),
        const FishSpecies(
          id: 'g025',
          standardName: '黄鳝',
          scientificName: 'Monopterus albus',
          aliases: ['鳝鱼'],
          category: FishCategory.freshwaterGeneral,
          rarity: FishRarity.uncommon,
          habitat: '稻田、池塘',
          behavior: '肉食性，夜行',
          fishingMethod: '蚯蚓、软饵',
          description: '无鳞淡水鱼',
          iconEmoji: '🐍',
        ),
        const FishSpecies(
          id: 'g026',
          standardName: '鳗鲡',
          scientificName: 'Anguilla japonica',
          aliases: ['鳗鱼'],
          category: FishCategory.freshwaterGeneral,
          rarity: FishRarity.rare,
          habitat: '江河入海口',
          behavior: '肉食性',
          fishingMethod: '活饵、软饵',
          description: '洄游性鱼类',
          iconEmoji: '🐍',
        ),
        const FishSpecies(
          id: 'g027',
          standardName: '河鳗',
          scientificName: 'Anguilla japonica',
          aliases: ['白鳝'],
          category: FishCategory.freshwaterGeneral,
          rarity: FishRarity.rare,
          habitat: '淡水流域',
          behavior: '肉食性',
          fishingMethod: '活饵',
          description: '鳗鲡的淡水形态',
          iconEmoji: '🐍',
        ),
        const FishSpecies(
          id: 'g028',
          standardName: '七丝鲚',
          scientificName: 'Coilia grayii',
          aliases: [],
          category: FishCategory.freshwaterGeneral,
          rarity: FishRarity.uncommon,
          habitat: '沿海海域',
          behavior: '杂食性',
          fishingMethod: '虫饵',
          description: '小型鱼类',
          iconEmoji: '🐟',
        ),
        const FishSpecies(
          id: 'g029',
          standardName: '凤尾鱼',
          scientificName: 'Coilia nasus',
          aliases: [],
          category: FishCategory.freshwaterGeneral,
          rarity: FishRarity.uncommon,
          habitat: '长江口',
          behavior: '杂食性',
          fishingMethod: '虫饵',
          description: '常见小型鱼',
          iconEmoji: '🐟',
        ),
        const FishSpecies(
          id: 'g030',
          standardName: '遮目鱼',
          scientificName: 'Chanos chanos',
          aliases: ['虱目鱼'],
          category: FishCategory.freshwaterGeneral,
          rarity: FishRarity.rare,
          habitat: '热带沿海',
          behavior: '草食性',
          fishingMethod: '素饵',
          description: '重要养殖鱼种',
          iconEmoji: '🐟',
        ),
        const FishSpecies(
          id: 'g031',
          standardName: '弹涂鱼',
          scientificName: 'Periophthalmus spp.',
          aliases: ['跳跳鱼'],
          category: FishCategory.freshwaterGeneral,
          rarity: FishRarity.rare,
          habitat: '滩涂、河口',
          behavior: '杂食性，可离水',
          fishingMethod: '虫饵',
          description: '能爬行跳跃',
          iconEmoji: '🐸',
        ),
        const FishSpecies(
          id: 'g032',
          standardName: '斗鱼',
          scientificName: 'Macropodus opercularis',
          aliases: ['中国斗鱼'],
          category: FishCategory.freshwaterGeneral,
          rarity: FishRarity.uncommon,
          habitat: '稻田、池塘',
          behavior: '杂食性',
          fishingMethod: '虫饵',
          description: '色彩艳丽的小型鱼',
          iconEmoji: '🐟',
        ),
        const FishSpecies(
          id: 'g033',
          standardName: '刺鳅',
          scientificName: 'Mastacembelus aculeatus',
          aliases: ['刀鳅'],
          category: FishCategory.freshwaterGeneral,
          rarity: FishRarity.uncommon,
          habitat: '南方淡水',
          behavior: '杂食性',
          fishingMethod: '虫饵',
          description: '背鳍有刺',
          iconEmoji: '🐍',
        ),
        const FishSpecies(
          id: 'g034',
          standardName: '鳜鱼',
          scientificName: 'Siniperca scherzeri',
          aliases: ['大眼鳜'],
          category: FishCategory.freshwaterGeneral,
          rarity: FishRarity.rare,
          habitat: '山涧溪流',
          behavior: '肉食性',
          fishingMethod: '活饵、软饵',
          description: '眼睛较大',
          iconEmoji: '🐟',
        ),
        const FishSpecies(
          id: 'g035',
          standardName: '暗纹东方鲀',
          scientificName: 'Takifugu fasciatus',
          aliases: ['河豚'],
          category: FishCategory.freshwaterGeneral,
          rarity: FishRarity.rare,
          habitat: '江河、河口',
          behavior: '肉食性，受惊充气',
          fishingMethod: '软饵',
          description: '有河豚毒素',
          iconEmoji: '🐡',
        ),
        const FishSpecies(
          id: 'g036',
          standardName: '黄鳍东方鲀',
          scientificName: 'Takifugu xanthopterus',
          aliases: ['河豚'],
          category: FishCategory.freshwaterGeneral,
          rarity: FishRarity.rare,
          habitat: '沿海海域',
          behavior: '肉食性',
          fishingMethod: '软饵',
          description: '鳍条黄色',
          iconEmoji: '🐡',
        ),
        const FishSpecies(
          id: 'g037',
          standardName: '菊黄东方鲀',
          scientificName: 'Takifugu flavidus',
          aliases: ['河豚'],
          category: FishCategory.freshwaterGeneral,
          rarity: FishRarity.legendary,
          habitat: '沿海海域',
          behavior: '肉食性',
          fishingMethod: '软饵',
          description: '体色菊黄',
          iconEmoji: '🐡',
        ),
        const FishSpecies(
          id: 'g038',
          standardName: '斑点鸡笼鲳',
          scientificName: 'Drepane punctata',
          aliases: ['鲳鱼'],
          category: FishCategory.freshwaterGeneral,
          rarity: FishRarity.uncommon,
          habitat: '沿海海域',
          behavior: '杂食性',
          fishingMethod: '虫饵',
          description: '体有斑点',
          iconEmoji: '🐟',
        ),
        const FishSpecies(
          id: 'g039',
          standardName: '灰鲳',
          scientificName: 'Pampus cinereus',
          aliases: ['鲳鱼'],
          category: FishCategory.freshwaterGeneral,
          rarity: FishRarity.uncommon,
          habitat: '沿海海域',
          behavior: '杂食性',
          fishingMethod: '虫饵、软饵',
          description: '体色灰白',
          iconEmoji: '🐟',
        ),
        const FishSpecies(
          id: 'g040',
          standardName: '刺鲳',
          scientificName: 'Psenopsis anomala',
          aliases: ['鲳鱼'],
          category: FishCategory.freshwaterGeneral,
          rarity: FishRarity.uncommon,
          habitat: '沿海海域',
          behavior: '杂食性',
          fishingMethod: '虫饵',
          description: '背鳍有刺',
          iconEmoji: '🐟',
        ),
        const FishSpecies(
          id: 'g041',
          standardName: '乌鲳',
          scientificName: 'Parastromateus niger',
          aliases: ['铁甲鲳'],
          category: FishCategory.freshwaterGeneral,
          rarity: FishRarity.uncommon,
          habitat: '热带海域',
          behavior: '杂食性',
          fishingMethod: '虫饵',
          description: '体色深灰',
          iconEmoji: '🐟',
        ),
        const FishSpecies(
          id: 'g042',
          standardName: '中颌鲑鲤',
          scientificName: 'Rafael & Goodes',
          aliases: [],
          category: FishCategory.freshwaterGeneral,
          rarity: FishRarity.rare,
          habitat: '淡水',
          behavior: '杂食性',
          fishingMethod: '软饵',
          description: '中型淡水鱼',
          iconEmoji: '🐟',
        ),
        const FishSpecies(
          id: 'g043',
          standardName: '圆口铜鱼',
          scientificName: 'Coreius guichenoti',
          aliases: ['铜鱼'],
          category: FishCategory.freshwaterGeneral,
          rarity: FishRarity.uncommon,
          habitat: '长江上游',
          behavior: '杂食性',
          fishingMethod: '虫饵',
          description: '体色铜黄',
          iconEmoji: '🐟',
        ),
        const FishSpecies(
          id: 'g044',
          standardName: '中华细鲫',
          scientificName: 'Aphyocypris chinensis',
          aliases: ['草鱼苗'],
          category: FishCategory.freshwaterGeneral,
          rarity: FishRarity.common,
          habitat: '南方淡水',
          behavior: '杂食性',
          fishingMethod: '虫饵',
          description: '常见小型淡水鱼',
          iconEmoji: '🐟',
        ),
        const FishSpecies(
          id: 'g045',
          standardName: '须鲫',
          scientificName: 'Carassius carassius',
          aliases: ['野生鲫鱼'],
          category: FishCategory.freshwaterGeneral,
          rarity: FishRarity.uncommon,
          habitat: '江河、湖泊',
          behavior: '杂食性',
          fishingMethod: '蚯蚓、红虫',
          description: '口须明显',
          iconEmoji: '🐟',
        ),
        const FishSpecies(
          id: 'g046',
          standardName: '短棘鲀',
          scientificName: 'Diodon spp.',
          aliases: ['刺河豚'],
          category: FishCategory.freshwaterGeneral,
          rarity: FishRarity.rare,
          habitat: '沿海海域',
          behavior: '杂食性，受惊充气',
          fishingMethod: '软饵',
          description: '体有短刺',
          iconEmoji: '🐡',
        ),
        const FishSpecies(
          id: 'g047',
          standardName: '六斑刺鲀',
          scientificName: 'Diodon holocanthus',
          aliases: ['刺河豚'],
          category: FishCategory.freshwaterGeneral,
          rarity: FishRarity.rare,
          habitat: '热带海域',
          behavior: '杂食性',
          fishingMethod: '软饵',
          description: '体有六斑',
          iconEmoji: '🐡',
        ),
        const FishSpecies(
          id: 'g048',
          standardName: '纹腹叉鼻鲀',
          scientificName: 'Arothron hispidus',
          aliases: ['气鼓鱼'],
          category: FishCategory.freshwaterGeneral,
          rarity: FishRarity.legendary,
          habitat: '热带海域',
          behavior: '杂食性',
          fishingMethod: '软饵',
          description: '腹部有纹',
          iconEmoji: '🐡',
        ),
        const FishSpecies(
          id: 'g049',
          standardName: '星点东方鲀',
          scientificName: 'Takifugu niphyperion',
          aliases: ['河豚'],
          category: FishCategory.freshwaterGeneral,
          rarity: FishRarity.legendary,
          habitat: '沿海海域',
          behavior: '肉食性',
          fishingMethod: '软饵',
          description: '体有星点',
          iconEmoji: '🐡',
        ),
        const FishSpecies(
          id: 'g050',
          standardName: '弓斑东方鲀',
          scientificName: 'Takifugu ocellatus',
          aliases: ['河豚'],
          category: FishCategory.freshwaterGeneral,
          rarity: FishRarity.rare,
          habitat: '江河入海口',
          behavior: '肉食性',
          fishingMethod: '软饵',
          description: '眼部有斑纹',
          iconEmoji: '🐡',
        ),
      ];

  /// 根据ID获取鱼类物种
  static FishSpecies? getById(String id) {
    try {
      return allSpecies.firstWhere((s) => s.id == id);
    } catch (_) {
      return null;
    }
  }

  /// 根据分类获取鱼类物种
  static List<FishSpecies> getByCategory(FishCategory category) {
    return allSpecies.where((s) => s.category == category).toList();
  }

  /// 根据稀有度获取鱼类物种
  static List<FishSpecies> getByRarity(FishRarity rarity) {
    return allSpecies.where((s) => s.rarity == rarity).toList();
  }

  /// 搜索鱼类物种
  static List<FishSpecies> search(String keyword) {
    if (keyword.isEmpty) return allSpecies;
    final lower = keyword.toLowerCase();
    return allSpecies.where((s) {
      return s.standardName.toLowerCase().contains(lower) ||
          s.aliases.any((a) => a.toLowerCase().contains(lower)) ||
          (s.scientificName?.toLowerCase().contains(lower) ?? false);
    }).toList();
  }
}
