import 'app_strings.dart';

/// English locale strings
const AppStrings englishStrings = AppStrings(


    appName: 'LureBox',
    home: 'Home',
    fishList: 'Fish List',
    equipment: 'Equipment',
    achievement: 'Achievement',
    viewAchievements: 'View your fishing achievements',
    me: 'Me',
    settings: 'Settings',
    dataManagement: 'Data Management',
    appearanceSettings: 'Appearance',
    appearanceSettingsDesc: 'Dark mode, language',
    fishCount: 'Total Catch',
    release: 'Release',
    keep: 'Keep',
    releaseRate: 'Release Rate',
    species: 'Species',
    length: 'Length',
    weight: 'Weight',
    location: 'Location',
    time: 'Time',
    rod: 'Rod',
    reel: 'Reel',
    lure: 'Lure',
    rodLength: 'Length',
    rodHardness: 'Hardness',
    rodAction: 'Action',
    rodMaterial: 'Material',
    weightRange: 'Weight Range',
    reelRatio: 'Gear Ratio',
    reelCapacity: 'Spool Capacity',
    reelBrakeType: 'Brake Type',
    reelWeight: 'Reel Weight',
    reelWeightHint: 'e.g.: 200',
    line: 'Line',
    lureType: 'Type',
    lureWeight: 'Weight',
    lureSize: 'Size',
    lureColor: 'Color',
    todayCatch: 'Today',
    monthCatch: 'This Month',
    yearCatch: 'This Year',
    allCatch: 'All Time',
    personalRecord: 'Personal Record',
    noData: 'No Data',
    noCatchYet: 'No catch records yet',
    goCatchFish: 'Go catch your first fish!',
    recordCatch: 'Record Catch',
    edit: 'Edit',
    share: 'Share',
    template: 'Template',
    showStats: 'Show Stats',
    showHashtags: 'Show Hashtags',
    showWatermark: 'Show Watermark',
    delete: 'Delete',
    save: 'Save',
    cancel: 'Cancel',
    confirm: 'Confirm',
    loading: 'Loading...',
    error: 'Error',
    retry: 'Retry',
    about: 'About',
    version: 'Version',
    unitSettings: 'Unit Settings',
    lengthUnit: 'Length Unit',
    weightUnit: 'Weight Unit',
    unit: 'Unit',
    darkMode: 'Dark Mode',
    language: 'Language',
  watermarkSettings: 'Watermark Settings',
  watermarkSettingsDesc: 'Custom watermark style',
  watermarkManagement: 'Watermark Management',
  watermarkManagementDesc: 'Custom watermark style',
  backupAndExport: 'Backup & Export',
  backupAndExportDesc: 'Data backup and export management',
  fileManagement: 'File Management',
  fileManagementDesc: 'View and manage export/backup files',
  exportCsv: 'Export CSV',
  exportCsvDesc: 'Export catch records as CSV spreadsheet',
  fullBackup: 'Full Backup',
  fullBackupDesc: 'Export ZIP backup with database and photos',
  restoreBackup: 'Restore Backup',
  restoreBackupDesc: 'Restore data from ZIP backup file',
    watermarkEnabled: 'Watermark Enabled',
    watermarkDisabled: 'Watermark Disabled',
    displayInfo: 'Display Info',
    dataBackup: 'Data Backup',
    webdavBackup: 'WebDAV Backup',
    exportData: 'Export Data',
    importData: 'Import Data',
    exportTo: 'Export to local file',
    importFrom: 'Import from local file',
    serverAddress: 'Server Address',
    username: 'Username',
    password: 'Password',
    connect: 'Connect',
    exportSuccess: 'Export success',
    importSuccess: 'Import success',
    exportFailed: 'Export failed',
    importFailed: 'Import failed',
    connectFailed: 'Connection failed',
    connecting: 'Connecting...',
    connected: 'Connected',
    disconnected: 'Disconnected',
    connectSuccess: 'Connection success',
    exportFunction: 'Export function in development...',
    importFunction: 'Import function in development...',
    webdavFunction: 'WebDAV function in development...',
    connectWebdav: 'Sync to cloud',
    serverAddressHint: 'https://dav.example.com',
    usernameHint: 'Enter username',
    passwordHint: 'Enter password',
    exportDataHint: 'Export to local file',
    importDataHint: 'Import from local file',
    speciesDistribution: 'Species Distribution',
    trendAnalysis: 'Trend Analysis',
    locationAnalysis: 'Location Analysis',
    equipmentDistribution: 'Equipment Distribution',
    fishDetail: 'Fish Detail',
    totalWeight: 'Total Weight',
    status: 'Status',
    today: 'Today',
    month: 'Month',
    year: 'Year',
    all: 'All',
    byDay: 'By Day',
    byMonth: 'By Month',
    byYear: 'By Year',
    last30Days: 'Last 30 Days',
    last12Months: 'Last 12 Months',
    yearlyTrend: 'Yearly Trend',
    hourlyTrend: 'Hourly Trend',
    dailyTrend: 'Daily Trend',
    monthlyTrend: 'Monthly Trend',
    fishRod: 'Rod',
    fishReel: 'Reel',
    fishLure: 'Lure',
    protectionEcology: 'Protect Aquatic Ecology',
    reasonableRelease:
        'Release responsibly, keep big release small, fish ethically',
    fromLureBox: '\u200BFrom LureBox',
    yourFishingAssistant: 'LureBox - Your Fishing Assistant',
    fishCountUnit: '',
    hour: ':00',
    day: '',
    monthUnit: '',
    yearUnit: '',
    total: 'Total',
    quantity: 'Quantity',
    search: 'Search',
    searchHint: 'Search by species or location',
    selectDateRange: 'Select Date Range',
    custom: 'Custom',
    confirmDelete: 'Confirm Delete',
    confirmDeleteSelected: 'Delete selected',
    records: 'records',
    selected: 'Selected',
    items: 'items',
    selectAll: 'Select All',
    thisWeek: 'This Week',
    thisMonth: 'This Month',
    thisYear: 'This Year',
    fate: 'Fate',
    clearFilters: 'Clear Filters',
    filterActive: 'Filters active, tap to modify',
    expandFilter: 'Tap to expand filters',
    filter: 'Filter',
    done: 'Done',
    noFishFound: 'No fish found',
    noMatchFound: 'No matching fish found',
    cameraNotReady: 'Camera not ready',
    switchCameraFailed: 'Failed to switch camera',
    takePhotoFirst: 'Please take a photo first',
    enterSpecies: 'Please enter species',
    enterValidLength: 'Please enter valid length',
    enterValidWeight: 'Please enter valid weight',
    saveFailed: 'Save failed',
    switchCamera: 'Switch Camera',
    initializingCamera: 'Initializing camera...',
    retake: 'Retake',
    enterSpeciesName: 'Enter species name',
    enterLength: 'Enter length',
    optional: 'optional',
    estimated: 'Estimated',
    estimatedWeight: 'Estimated weight',
    enterActualWeight: 'Enter actual weight',
    useEquipment: 'Equipment Used',
    modify: 'Modify',
    catchLocation: 'Catch Location',
    catchTime: 'Catch Time',
    confirmSave: 'Confirm Save',
    cameraPermissionRequired: 'Camera permission required to take photos',
    noCameraFound: 'No camera found',
    cameraInitFailed: 'Camera initialization failed',
    centimeter: 'cm',
    inch: 'in',
    kilogram: 'kg',
    pound: 'lb',
    meter: 'm',
    foot: 'ft',
    gram: 'g',
    ounce: 'oz',
    kilometer: 'km',
    mile: 'mi',
    celsius: '°C',
    fahrenheit: '°F',
    temperature: 'Temperature',
    millimeter: 'mm',
    unitsSettings: 'Unit Settings',
    followSystem: 'Follow System',
    off: 'Off',
    on: 'On',
    simplifiedChinese: 'Simplified Chinese',
    enabled: 'Enabled',
    disabled: 'Disabled',
    locationManagement: 'Location Management',
    locationManagementDesc: 'Manage locations, merge similar ones',
    speciesManagement: 'Species Management',
    speciesManagementDesc: 'Manage fish species, edit common species',
    aiConfiguration: 'AI Configuration',
    aiConfigurationDesc: 'Configure AI recognition settings',
    exportAndBackupManagement: 'Export & Backup',
    exportAndBackupManagementDesc: 'Export data or backup to cloud',
    syncToCloud: 'Sync to Cloud',
    exportToLocal: 'Export to local file',
    importFromLocal: 'Import from local file',
    appDescription: 'A catch recording tool designed for fishing enthusiasts.',
    features: 'Features:',
    gotIt: 'Got it',
    webdavSettings: 'WebDAV Settings',
    noAchievementData: 'No achievement data',
    completed: 'Completed',
    specialAchievement: 'Special Achievement',
    completion: 'Completion',
    achievementOverview: 'Achievement Overview',
    unlocked: 'Unlocked',
    totalAchievements: 'Total Achievements',
    achievementUnit: ' achievements',
    remainingAchievements: 'Need \$count more achievements',
    noAchievements: 'No achievements',
    achieved: 'Achieved',
    editEquipment: 'Edit Equipment',
    addEquipment: 'Add Equipment',
    basicInfo: 'Basic Info',
    brand: 'Brand',
    brandHint: 'Daiwa, Shimano',
    model: 'Model',
    modelHint: 'e.g., Certate',
    price: 'Price',
    priceHint: 'e.g., 1999',
    invalidPrice: 'Please enter valid price',
    priceTooHigh: 'Price cannot exceed 1,000,000',
    purchaseDate: 'Purchase Date',
    tapToSelect: 'Tap to select',
    setDefault: 'Set as Default',
    autoAssociate: 'Auto-associate when recording',
    rodParameters: 'Rod Parameters',
    gunHandle: 'Casting',
    spinningHandle: 'Spinning',
    handleType: 'Handle Type',
    handleTypeHint: 'Casting/Spinning',
    usageType: 'Usage Type',
    selectOrEnterUsage: 'Select or enter usage',
    reelParameters: 'Reel Parameters',
    baitcaster: 'Baitcaster',
    spinningReel: 'Spinning Reel',
    reelType: 'Reel Type',
    reelTypeHint: 'Baitcaster/Spinning',
    reelUsageHint: 'Distance/All-round/Finesse',
    lineInfo: 'Line Info',
    brandAndName: 'Brand & Name',
    lineBrandHint: 'e.g., YGK, Varivas',
    lineNumber: 'Line Number',
    lineNumberHint: 'e.g., 0.8',
    lineLength: 'Line Length',
    lineLengthHint: 'e.g., 150m',
    lineDate: 'Line Date',
    lureParameters: 'Lure Parameters',
    type: 'Type',
    selectOrEnterType: 'Select or enter type',
    myEquipment: 'My Equipment',
    expandAll: 'Expand All',
    collapseAll: 'Collapse All',
    noEquipmentYet: 'No',
    noEquipmentAddHint: 'No equipment, tap to add',
    confirmDeleteEquipment: 'Delete this equipment?',
    defaultLabel: 'Default',
    unnamed: 'Unnamed',
    record: 'Record',
    selectEquipment: 'Select Equipment',
    manageEquipment: 'Manage Equipment',
    notSelected: 'Not selected',
    lengthHint: 'e.g., 1.8m',
    sections: 'Sections',
    sectionsHint: 'e.g., 2',
    material: 'Material',
    materialHint: 'e.g., Carbon',
    hardness: 'Hardness',
    hardnessHint: 'e.g., UL/L/M/MH/H',
    action: 'Action',
    actionHint: 'e.g., Fast/Medium/Slow',
    weightRangeHint: 'e.g., 1-7g',
    bearings: 'Bearings',
    bearingsHint: 'e.g., 6+1',
    jointType: 'Joint Type',
    jointTypeHint: 'e.g., Push/Pull',
    ratio: 'Gear Ratio',
    ratioHint: 'e.g., 5.2:1',
    ratioFront: 'front',
    ratioBack: 'back',
    capacityHint: 'e.g., 0.8/150',
    capacityLineUnit: '#/',
    brakeTypeHint: 'e.g., Magnetic/Centrifugal',
    lineType: 'Line Type',
    lineTypeHint: 'e.g., PE/Mono/Fluoro',
    lureTypeHint: 'e.g., Minnow/VIB/Soft',
    lureWeightHint: 'e.g., 7g/10g/14g',
    lureSizeHint: 'e.g., 5cm/7cm/10cm',
    lureColorHint: 'e.g., Silver/Gold/Glow',
    size: 'Size',
    selectAtLeast2Locations: 'Please select at least 2 locations to merge',
    confirmMerge: 'Confirm Merge',
    mergeLocationsTo: 'Merge locations to:',
    mergedLocations: 'Locations to merge:',
    mergeSuccess: 'Merge successful',
    mergeFailed: 'Merge failed',
    noAutoMergeLocations: 'No similar locations found',
    autoMerge: 'Auto Merge',
    found: 'Found',
    similarLocations: 'similar location groups',
    mergeTo: 'Merge to',
    mergeAll: 'Merge All',
    autoMergeSuccess: 'Auto merge successful',
    autoMergeFailed: 'Auto merge failed',
    mergeSelected: 'Merge Selected',
    groups: 'groups',
    noLocationRecords: 'No location records',
    enableWatermark: 'Enable Watermark',
    watermarkPosition: 'Watermark displayed at bottom-left',
    selectWatermarkInfo: 'Select info to display on watermark',
    watermarkPreview: 'Watermark Preview',
    watermarkPositionDesc: 'Watermark is fixed at bottom-left of photo',
    watermarkPositionTopLeft: 'Watermark is at top-left of photo',
    watermarkPositionTopRight: 'Watermark is at top-right of photo',
    watermarkPositionBottomLeft: 'Watermark is at bottom-left of photo',
    watermarkPositionBottomRight: 'Watermark is at bottom-right of photo',
    watermarkPositionCenter: 'Watermark is at center of photo',
    // Watermark Settings Page
    watermarkDragToSort: 'Long press to drag and sort',
    watermarkNotEnabled: 'Not Enabled',
    watermarkStyle: 'Watermark Style',
    watermarkBgRadius: 'Background Radius',
    watermarkBgOpacity: 'Background Opacity',
    watermarkFontSize: 'Font Size',
    watermarkTemplateSimple: 'Simple',
    watermarkTemplateSimpleDesc: 'Clean display at bottom-left',
    watermarkTemplateElegant: 'Elegant',
    watermarkTemplateElegantDesc: 'Dark frosted at bottom-right',
    watermarkTemplateBold: 'Bold',
    watermarkTemplateBoldDesc: 'Centered high contrast',
    watermarkTemplate: 'Template',
    watermarkColorWhite: 'White',
    watermarkColorBlack: 'Black',
    watermarkColorRed: 'Red',
    watermarkColorGreen: 'Green',
    watermarkColorBlue: 'Blue',
    watermarkColorYellow: 'Yellow',
    watermarkColorPurple: 'Purple',
    watermarkColorCyan: 'Cyan',
    watermarkFontColor: 'Font Color',
    watermarkPositionTopLeftLabel: 'Top Left',
    watermarkPositionTopRightLabel: 'Top Right',
    watermarkPositionBottomLeftLabel: 'Bottom Left',
    watermarkPositionBottomRightLabel: 'Bottom Right',
    watermarkPositionCenterLabel: 'Center',
    watermarkPositionLabel: 'Watermark Position',
    watermarkCustomText: 'Custom Text',
    watermarkCustomTextHint: 'Shown at watermark bottom (e.g. signature)',
    watermarkCustomTextPlaceholder: 'Optional, e.g. signature',
    watermarkPreviewSpecies: 'Mandarin Fish',
    watermarkPreviewLocation: 'West Lake, Hangzhou',
    rodDistribution: 'Rod Distribution',
    reelDistribution: 'Reel Distribution',
    lureDistribution: 'Lure Distribution',
    statistics: 'Statistics',
    catchStatistics: 'Catch Statistics',
    shareFailed: 'Share failed',
    confirmDeleteFish: 'Delete this catch record?',
    notFilled: 'Not filled',
    editFish: 'Edit Fish',
    mapLocation: 'Location Map',
    errorCameraPermission: 'Camera permission required',
    errorCameraInit: 'Camera initialization failed, please restart app',
    errorCameraSwitch: 'Failed to switch camera',
    errorLocationPermission: 'Location permission required',
    errorLocationFetch: 'Failed to get location',
    errorDatabaseRead: 'Failed to read data',
    errorDatabaseWrite: 'Failed to save data',
    errorFileDelete: 'Failed to delete file',
    errorFileExport: 'Failed to export file',
    errorFileImport: 'Failed to import file',
    errorNetworkConnect: 'Network connection failed',
    errorWebDAVConnect: 'WebDAV connection failed',
    errorWebDAVUpload: 'Failed to upload to WebDAV',
    errorWebDAVDownload: 'Failed to download from WebDAV',
    errorShareFailed: 'Share failed',
    errorSaveFailed: 'Save failed',
    errorLoadFailed: 'Load failed',
    errorDeleteFailed: 'Delete failed',
    errorUnknown: 'An unknown error occurred',
    rodHandleTypes: ['Casting', 'Spinning'],
    rodUsageTypes: [
      'Ultralight Finesse',
      'All-round',
      'Distance',
      'Worm/Jig',
      'Bass',
      'Power',
    ],
    reelTypes: ['Baitcaster', 'Spinning'],
    reelUsageTypes: ['Distance', 'All-round', 'Finesse', 'Power', 'Jigging'],
    lureTypeOptions: [
      'Minnow',
      'Popper',
      'Pencil',
      'Spinner',
      'Soft',
      'Jig',
      'VIB',
      'Crank',
      'Other',
    ],
    unknownEquipment: 'Unknown',
    equipmentOverview: 'Equipment Overview',
    totalEquipment: 'Total',
    brandDistribution: 'Brand Distribution',
    equipmentCatchStats: 'Equipment Stats',
    equipmentId: 'Equipment',
    quantityStats: 'Quantity Stats',
    equipmentCatchRanking: 'Equipment Ranking',
    noCatchData: 'No catch data yet',
    selectFromGallery: 'Select from gallery',
    zoomIn: 'Zoom In',
    zoomOut: 'Zoom Out',
    locateMe: 'Locate Me',
    noLocationCoordinates: 'No location coordinates',
    noLocationCoordinatesHint: 'Enable location when recording catches',
    lastVisit: 'Last Visit',
    noRecords: 'No records',
    coordinates: 'Coordinates',
    navigate: 'Navigate',
    cannotOpenMapApp: 'Cannot open map app',
    locationPermissionDenied: 'Location permission denied',
    locationTimeout: 'Location timeout',
    geocodingTimeout: 'Geocoding timeout',
    unknownLocation: 'Unknown location',
    catchCount: 'Catch Count',
    exportFormat: 'Export Format',
    csvTable: 'CSV Table',
    csvDescription: 'For Excel / data analysis',
    jsonFullBackup: 'JSON Full Backup',
    jsonDescription: 'Complete backup of all data',
    exportingCsv: 'Exporting CSV...',
    csvExportSuccess: 'CSV export successful',
    generationFailed: 'Generation failed',
    exportingJson: 'Exporting JSON...',
    lureboxBackup: 'LureBox Backup',
    exporting: 'Exporting',
    generatingCsvFile: 'Generating CSV file...',
    exportConfirm: 'Export Confirm',
    confirmExport: 'Confirm Export',
    willExportNRecords: 'Will export \$count records',
    exportOptions: 'Export Options',
    format: 'Format',
    yes: 'Yes',
    no: 'No',
    previewFirstN: 'Preview (first \$count)',
    moreRecordsRemaining: '... and \$count more records',
    exportNRecords: 'Export \$count records',
    noMatchingRecords: 'No matching records',
    allTime: 'All Time',
    startDate: 'Start',
    now: 'Now',
    timeRange: 'Time Range',
    speciesFilter: 'Species Filter',
    clear: 'Clear',
    otherOptions: 'Other Options',
    includeImagePaths: 'Include Image Paths',
    includeLocationInfo: 'Include Location Info',
    confirmImportFile: 'Import data?',
    importingData: 'Importing...',
    importedCount: 'Imported \$count records',
    pleaseFillCompleteInfo: 'Please fill in all information',
    uploading: 'Uploading...',
    enumerationSeparator: ', ',
    catchRecordsExport: 'Catch Records Export',
    allRecords: 'All Records',
    dateRangeTo: 'to',
    // UI Labels
    address: 'Address',
    weather: 'Weather',
    tapToSet: 'Tap to set',
    pendingRecognition: 'Pending',
    addToPendingRecognition: '⏭ Add to pending',
    cancelPendingRecognition: '↩ Cancel pending',
    ascending: 'Ascending',
    descending: 'Descending',
    noEquipment: 'No equipment',
    hideLocation: 'Hide spots',
    showLocation: 'Show spots',
    totalCountPattern: 'Total: %d',
    speciesCountPattern: '%s: %d',
    rodUnit: '',
    reelUnit: '',
    lureUnit: '',
    configureRig: 'Configure Rig',
    rigType: 'Rig Type',
    sinkerConfig: 'Sinker Config',
    sinkerWeight: 'Sinker Weight',
    sinkerPosition: 'Sinker Position',
    hookConfig: 'Hook Config',
    hookWeight: 'Hook Weight',
    hookSize: 'Hook Size',
    customOption: 'Custom',
    customRigTypeHint: 'Enter custom rig type',
    customHookTypeHint: 'Enter custom hook type',
    pendingFishCountPattern:
        'You have %d fish catches pending species recognition',
    goToSpeciesManagement: 'Go to species management',
    airTemperature: 'Air Temp',
    pressure: 'Pressure',
    weatherInfo: 'Weather Info',
    // 天气描述（WMO）
    weatherClear: 'Clear',
    weatherMainlyClear: 'Mainly Clear',
    weatherPartlyCloudy: 'Partly Cloudy',
    weatherOvercast: 'Overcast',
    weatherFog: 'Fog',
    weatherDrizzle: 'Drizzle',
    weatherFreezingDrizzle: 'Freezing Drizzle',
    weatherRain: 'Rain',
    weatherFreezingRain: 'Freezing Rain',
    weatherSnowFall: 'Snowfall',
    weatherSnowGrains: 'Snow Grains',
    weatherRainShowers: 'Rain Showers',
    weatherSnowShowers: 'Snow Showers',
    weatherThunderstorm: 'Thunderstorm',
    weatherThunderstormHail: 'Thunderstorm with Hail',
    weatherUnknown: 'Unknown',
    // 天气选项
    weatherOption0: '☀️ Clear',
    weatherOption1: '⛅ Mainly Clear',
    weatherOption2: '☁️ Cloudy',
    weatherOption3: '🌧️ Drizzle',
    weatherOption4: '⛈️ Thunderstorm',
    weatherOption5: '❄️ Snow',
    weatherOption6: '🌫️ Fog',
    // 相机/编辑页面
    modifyCatchLocation: 'Modify Catch Location',
    locationName: 'Location Name',
    modifyWeather: 'Modify Weather',
    notSet: 'Not Set',
    onboardingSkip: 'Skip',
    onboardingGetStarted: 'Get Started',
    onboardingNext: 'Next',
    onboardingWelcomeTitle: 'Welcome to LureBox',
    onboardingWelcomeDesc: 'Record every catch from your fishing trips',
    onboardingFeaturesTitle: 'Features',
    onboardingFeatureCameraTitle: 'Photo Capture',
    onboardingFeatureCameraDesc: 'Quickly photograph your catches',
    onboardingFeatureEquipmentTitle: 'Equipment Manager',
    onboardingFeatureEquipmentDesc: 'Manage rods, reels, and lures',
    onboardingFeatureStatsTitle: 'Statistics',
    onboardingFeatureStatsDesc: 'View catch data trends',
    onboardingFeatureBackupTitle: 'Data Backup',
    onboardingFeatureBackupDesc: 'Cloud backup never loses data',
    onboardingPermissionsTitle: 'Permissions',
    onboardingPermissionCameraTitle: 'Camera',
    onboardingPermissionCameraDesc: 'Used to photograph your catches',
    onboardingPermissionCameraExample: 'Example: Capture memorable fishing moments',
    onboardingPermissionLocationTitle: 'Location',
    onboardingPermissionLocationDesc: 'Record fishing spot locations',
    onboardingPermissionLocationExample: 'Example: Auto-record spot coordinates',
    onboardingPrivacyNote: 'We do not collect or upload your private data',
    onboardingSettingsTitle: 'Personalization',
    onboardingSettingsDesc: 'Adjustable anytime in settings',
    onboardingSettingsItems: 'Units, Theme, Language',
    onboardingReadyTitle: 'All Set!',
    onboardingReadyDesc: 'Start recording your first catch',
    recognize: 'Recognize',
    notUsing: 'Not Using',
    sharing: 'Sharing...',
    distribution: 'Distribution',
    fishListTitle: 'Fish List',
    locationCancelSelect: 'Cancel Selection',
    locationMergeTo: 'Merge To',
    locationEnterTargetName: 'Enter target name',
    locationCount: 'Location Count',
    locationTotalFishCount: 'Total Fish Count',
    locationSmartMergeSuggestion: 'Smart Merge Suggestions',
    locationStartFishing: 'Start recording your fishing trips!',
    locationEditName: 'Edit Location Name',
    locationNewName: 'New Name',
    locationEnterNewName: 'Enter new location name',
    locationEditSuccess: 'Updated successfully',
    locationEditFailed: 'Update failed',
    locationMergeConfirm: 'Confirm Merge',
    locationConfirmAutoMerge: 'Confirm Auto Merge',
    locationAutoMergeConfirm: 'Merge %d similar locations into "%s"? This cannot be undone.',
    locationSearchHint: 'Search locations',
    speciesManualRecognition: 'Manual Recognition',
    speciesAssignToCatches: 'Assign species to the following catches:',
    speciesNameLabel: 'Species Name',
    speciesConfirm: 'Confirm',
    speciesAiResult: 'AI Result: %s',
    speciesConfidence: 'Confidence: %.1f%%',
    speciesEditableName: 'Species Name (editable)',
    speciesRename: 'Rename Species',
    speciesEnterNewName: 'Enter new species name',
    speciesConfirmDelete: 'Confirm Delete',
    speciesDeleteConfirmMsg: 'Delete species "%s"? Related catch records will become unknown.',
    speciesUpdated: 'Updated species: %s',
    speciesUpdateFailed: 'Update failed',
    speciesRenamed: 'Renamed "%s" to "%s"',
    speciesRenameFailed: 'Rename failed',
    speciesDeleted: 'Deleted species "%s" (%d records)',
    speciesDeleteFailed: 'Delete failed',
    speciesNoRecords: 'No species records',
    speciesRecognitionComplete: 'Recognition complete: %d succeeded, %d failed',
    speciesSaved: 'Species saved',
    speciesImageNotFound: 'Image not found',
    speciesConfigureApiKey: 'Please configure AI Recognition API Key first',
    speciesAiResultTitle: 'AI Recognition Result',
    speciesAlternative: 'Alternative',
    speciesNoResult: 'No recognition result',
    speciesRecognitionFailed: 'Recognition failed: %s',
    aiConfigTitle: 'AI Configuration',
    aiProviderLabel: 'AI Provider',
    aiCurrentProvider: 'Current AI provider',
    aiConfigured: 'Configured',
    aiNotConfigured: 'Not Configured',
    aiConfigureProvider: 'Configure %s',
    aiEnterApiKey: 'Enter your API Key',
    aiPleaseEnterApiKey: 'Please enter API Key',
    aiBaseUrlRequired: 'Base URL (required)',
    aiBaseUrlOptional: 'Base URL (optional)',
    aiOpenaiEndpointRequired: 'OpenAI compatible API endpoint, required',
    aiCustomRequiresBaseUrl: 'Custom provider requires Base URL',
    aiModelNameOptional: 'Model Name (optional)',
    aiSpecifyModelName: 'Specify the model name to use',
    aiTestConnection: 'Test Connection',
    aiSaving: 'Saving...',
    aiConnectionSuccess: 'Connected! API Key is valid.',
    aiConnectionFailed: 'Connection failed: %s',
    aiConfigSaved: 'Configuration saved',
    pendingRecognitionList: 'Pending Recognition',
    pendingNoFish: 'No pending fish',
    pendingAiRecognition: 'AI Recognition',
    pendingManual: 'Manual',
    pendingRecognizing: 'Recognizing...',
    pendingRecognitionProgress: 'Recognizing: %d/%d (Success: %d, Failed: %d)',
    pendingBatchRecognition: 'Batch AI Recognition',
    pendingFishCount: '%d fish',
    deleteSuccess: 'Deleted successfully',
    exportFailedMsg: 'Export failed',
    fullBackupTitle: 'Full Backup',
    fullBackupCreateDesc: 'Creates a complete backup including database and all photos. File saved to device storage.',
    startBackup: 'Start Backup',
    creatingBackup: 'Creating backup',
    backupRunning: 'Backup is running in background, please wait...',
    backupComplete: 'Backup complete. File saved to local storage.',
    backupFailed: 'Backup failed',
    restoreTitle: 'Restore Backup',
    restoreOverwriteWarning: 'Restoring will overwrite all current data. This cannot be undone. Continue?',
    continueAction: 'Continue',
    restoreSuccessMsg: 'Restore successful',
    restoreFailedMsg: 'Restore failed',
    restoreDetailPattern: 'Fish: %d / Equipment: %d / Photos: %d',
    csvExport: 'CSV Export',
    jsonExport: 'JSON Export',
    lureboxCompleteBackup: 'LureBox Full Backup',
    lureboxDataExport: 'LureBox Data Export',
    uploadingToCloud: 'Uploading...',
    backupUploaded: 'Backup uploaded to cloud',
    uploadFailed: 'Upload failed',
    testing: 'Testing...',
    webdavTitle: 'WebDAV Backup',
    webdavConfigureServer: 'Configure WebDAV server for cloud backup',
    webdavSupportedUrl: 'WebDAV protocol URL',
    webdavPleaseEnterAddress: 'Please enter server address',
    webdavUrlMustStartHttp: 'URL must start with http:// or https://',
    webdavPleaseEnterUsername: 'Please enter username',
    webdavPleaseEnterPassword: 'Please enter password',
    backupNow: 'Backup Now',
    testFailed: 'Test failed',
    cameraInitTimeout: 'Camera initialization timeout',
    speciesHistoryTimeout: 'Species history loading timeout',
    equipmentLoadTimeout: 'Equipment loading timeout',
    locationFetchTimeout: 'Location fetch timeout',
    saveFailedCheckInput: 'Save failed, please check input',
    saveFailedRetry: 'Save failed, please retry',
    savedLabel: 'Set',
    notSavedLabel: 'Not Set',
    errorDeviceLocationOff: 'Please enable device location services',
    errorContextInvalid: 'Context is no longer valid',
    errorPermanentlyDenied: 'Permanently denied. Please enable in system settings.',
    errorDenied: 'Denied. Please enable in system settings.',
    errorRejected: 'Rejected',
    permissionRequiredTitle: '%s Required',
    permissionOpenSettings: 'Open Settings',
    privacyNote: 'We do not collect or upload your data. All information is stored locally on your device.',
    permissionGrantLater: 'Not Now',
    permissionGrant: 'Grant',
    unknownSpecies: 'Unknown Species',
    errorImageNotFound: 'Image file not found',
    errorImageTooLarge: 'Image exceeds 10MB limit',
    errorUnsupportedFormat: 'Unsupported format. Use JPG, PNG, or WebP.',
    errorApiKeyNotConfigured: 'API key not configured',
    errorProviderDisabled: 'Current provider is disabled',
    errorUnknownProvider: 'Unknown recognition provider',
    similarLocationsLabel: 'Similar locations: ',
    containsNSimilarLocations: 'Contains %d similar locations',
    mergeButton: 'Merge',
    fishCountSuffix: '%d fish',
    unlockProgress: 'Unlock Progress',
    speciesCountPattern2: '%d / %d species',
    monthlyNewSpecies: 'This month: +%d species',
    categoryQuantity: 'Quantity',
    categorySize: 'Size',
    categorySpecies: 'Species',
    categoryLocation: 'Location',
    categoryEquipment: 'Equipment',
    categoryEco: 'Eco',
    rodSection1: '1 Section',
    rodSection2: '2 Sections',
    rodSection3: '3 Sections',
    rodSectionMulti: 'Multi-Section',
    jointMethod: 'Joint Method',
    jointTypeSpigot: 'Spigot',
    jointTypeReverseSpigot: 'Reverse Spigot',
    jointTypeDragonSpigot: 'Dragon Spigot',
    jointTypeTelescopic: 'Telescopic',
    rodActionSS: 'SS (Ultra Slow)',
    rodActionS: 'S (Slow)',
    rodActionMR: 'MR (Medium Slow)',
    rodActionR: 'R (Medium)',
    rodActionRF: 'RF (Medium Fast)',
    rodActionF: 'F (Fast)',
    rodActionFF: 'FF (Extra Fast)',
    rodActionXF: 'XF (Ultra Fast)',
    baitWeightLabel: 'Bait Weight',
    minValue: 'Min',
    maxValue: 'Max',
    lineLabel: 'Line #',
    lineCapacity: 'Length',
    brakeTypeTraditionalMagnetic: 'Traditional Magnetic',
    brakeTypeCentrifugal: 'Centrifugal',
    brakeTypeDC: 'DC Brake',
    brakeTypeFloatingMagnetic: 'Floating Magnetic',
    brakeTypeInnovative: 'Innovative Combo',
    quantityUnitPiece: 'pcs',
    quantityUnitItem: 'items',
    quantityUnitPack: 'packs',
    quantityUnitBox: 'boxes',
    quantityUnitCarton: 'cartons',
    cardJointMethod: 'Joint',
    cardAction: 'Action',
    cardStrength: 'Strength',
    cardColor: 'Color',
    quantityPrefix: 'Qty: ',
    typeSpinningRod: 'Spinning Rod',
    typeBaitcastingRod: 'Baitcasting Rod',
    typeFlyRod: 'Fly Rod',
    typeTrollingRod: 'Trolling Rod',
    typeSpinningReel: 'Spinning Reel',
    typeBaitcastingReel: 'Baitcasting Reel',
    typeFlyReel: 'Fly Reel',
    typeTrollingReel: 'Trolling Reel',
    typeHardBait: 'Hard Bait',
    typeSoftBait: 'Soft Bait',
    typeSpoon: 'Spoon',
    typeJigHead: 'Jig Head',
    typeNylonLine: 'Nylon Line',
    typePELine: 'PE Line',
    typeFluorocarbonLine: 'Fluorocarbon',
    countSuffix: ' fish',
    distributionTitle: 'Distribution',
    priceDistribution: 'Price Distribution',
  );

