/// Onboarding page strings
mixin OnboardingStringsMixin {
  String get onboardingSkip;
  String get onboardingGetStarted;
  String get onboardingNext;
  String get onboardingWelcomeTitle;
  String get onboardingWelcomeDesc;
  String get onboardingFeaturesTitle;
  String get onboardingFeatureCameraTitle;
  String get onboardingFeatureCameraDesc;
  String get onboardingFeatureEquipmentTitle;
  String get onboardingFeatureEquipmentDesc;
  String get onboardingFeatureStatsTitle;
  String get onboardingFeatureStatsDesc;
  String get onboardingFeatureBackupTitle;
  String get onboardingFeatureBackupDesc;
  String get onboardingPermissionsTitle;
  String get onboardingPermissionCameraTitle;
  String get onboardingPermissionCameraDesc;
  String get onboardingPermissionCameraExample;
  String get onboardingPermissionLocationTitle;
  String get onboardingPermissionLocationDesc;
  String get onboardingPermissionLocationExample;
  String get onboardingPrivacyNote;
  String get onboardingSettingsTitle;
  String get onboardingSettingsDesc;
  String get onboardingSettingsItems;
  String get onboardingReadyTitle;
  String get onboardingReadyDesc;
}
