import 'package:lurebox/core/constants/strings/app_strings.dart';

/// Chinese locale strings
const AppStrings chineseStrings = AppStrings(


    appName: '路亚鱼护',
    home: '主页',
    fishList: '鱼护',
    equipment: '装备',
    achievement: '成就',
    viewAchievements: '查看你的钓鱼成就',
    me: '我的',
    settings: '设置',
    dataManagement: '数据管理',
    appearanceSettings: '外观与语言',
    appearanceSettingsDesc: '深色模式、语言',
    fishCount: '渔获总数',
    release: '放流',
    keep: '保留',
    releaseRate: '放流率',
    species: '品种',
    length: '长度',
    weight: '重量',
    location: '钓点',
    time: '时间',
    rod: '鱼竿',
    reel: '渔轮',
    lure: '鱼饵',
    rodLength: '长度',
    rodHardness: '硬度',
    rodAction: '调性',
    rodMaterial: '材质',
    weightRange: '适用饵重',
    reelRatio: '齿轮比',
    reelCapacity: '线杯容量',
    reelBrakeType: '刹车类型',
    reelWeight: '渔轮重量',
    reelWeightHint: '如：200',
    line: '鱼线',
    lureType: '类型',
    lureWeight: '重量',
    lureSize: '尺寸',
    lureColor: '颜色',
    todayCatch: '今日渔获',
    monthCatch: '本月渔获',
    yearCatch: '本年渔获',
    allCatch: '全部渔获',
    personalRecord: '个人记录',
    noData: '暂无数据',
    noCatchYet: '还没有鱼获记录',
    goCatchFish: '快去钓第一条鱼吧！',
    recordCatch: '记录鱼获',
    edit: '编辑',
    share: '分享',
    template: '模板',
    showStats: '显示统计',
    showHashtags: '显示标签',
    showWatermark: '显示水印',
    delete: '删除',
    save: '保存',
    cancel: '取消',
    confirm: '确认',
    loading: '正在加载...',
    error: '加载失败',
    retry: '重试',
    about: '关于',
    version: '版本',
    unitSettings: '单位设置',
    lengthUnit: '长度单位',
    weightUnit: '重量单位',
    unit: '单位',
    darkMode: '深色模式',
    language: '语言',
  watermarkSettings: '水印设置',
  watermarkSettingsDesc: '自定义水印样式',
  watermarkManagement: '水印管理',
  watermarkManagementDesc: '自定义水印样式',
  backupAndExport: '备份和导出',
  backupAndExportDesc: '数据备份与导出管理',
  fileManagement: '文件管理',
  fileManagementDesc: '查看和管理导出备份文件',
  exportCsv: '导出 CSV',
  exportCsvDesc: '导出渔获记录为 CSV 表格',
  fullBackup: '完整备份',
  fullBackupDesc: '导出包含数据库和照片的ZIP备份',
  restoreBackup: '恢复备份',
  restoreBackupDesc: '从ZIP备份文件恢复数据',
    watermarkEnabled: '水印已开启',
    watermarkDisabled: '水印已关闭',
    displayInfo: '显示信息',
    dataBackup: '数据备份',
    webdavBackup: 'WebDAV备份',
    exportData: '导出数据',
    importData: '导入数据',
    exportTo: '导出到本地文件',
    importFrom: '从本地文件导入',
    serverAddress: '服务器地址',
    username: '用户名',
    password: '密码',
    connect: '连接',
    exportSuccess: '导出成功',
    importSuccess: '导入成功',
    exportFailed: '导出失败',
    importFailed: '导入失败',
    connectFailed: '连接失败',
    connecting: '连接中...',
    connected: '已连接',
    disconnected: '未连接',
    connectSuccess: '连接成功',
    exportFunction: '导出功能开发中...',
    importFunction: '导入功能开发中...',
    webdavFunction: 'WebDAV功能开发中...',
    connectWebdav: '同步到云端',
    serverAddressHint: 'https://dav.example.com',
    usernameHint: '请输入用户名',
    passwordHint: '请输入密码',
    exportDataHint: '导出到本地文件',
    importDataHint: '从本地文件导入',
    speciesDistribution: '品种分布',
    trendAnalysis: '趋势分析',
    locationAnalysis: '钓点分析',
    equipmentDistribution: '装备使用分布',
    fishDetail: '渔获明细',
    totalWeight: '总重',
    status: '状态',
    today: '今日',
    month: '本月',
    year: '本年',
    all: '全部',
    byDay: '分日',
    byMonth: '分月',
    byYear: '分年',
    last30Days: '近30天趋势',
    last12Months: '近12月趋势',
    yearlyTrend: '年度趋势',
    hourlyTrend: '分时趋势',
    dailyTrend: '分日趋势',
    monthlyTrend: '月度趋势',
    fishRod: '鱼竿',
    fishReel: '渔轮',
    fishLure: '鱼饵',
    protectionEcology: '保护水生生态',
    reasonableRelease: '合理放流，留大放小，文明作钓',
    fromLureBox: '\u200B来自路亚鱼护',
    fishCountUnit: '条',
    hour: '时',
    day: '日',
    monthUnit: '月',
    yearUnit: '年',
    total: '共',
    quantity: '数量',
    search: '搜索',
    searchHint: '输入品种或地点搜索',
    selectDateRange: '选择日期范围',
    custom: '自定义',
    confirmDelete: '确认删除',
    confirmDeleteSelected: '确定删除选中的',
    records: '条记录',
    selected: '已选',
    items: '项',
    selectAll: '全选',
    thisWeek: '本周',
    thisMonth: '本月',
    thisYear: '本年',
    fate: '归宿',
    clearFilters: '清除筛选',
    filterActive: '筛选条件已生效，点击展开修改',
    expandFilter: '点击展开筛选',
    filter: '筛选',
    done: '完成',
    noFishFound: '没有找到鱼获',
    noMatchFound: '未找到匹配的鱼获',
    cameraNotReady: '相机未就绪',
    switchCameraFailed: '切换摄像头失败',
    takePhotoFirst: '请先拍照',
    enterSpecies: '请填写品种',
    enterValidLength: '请填写有效的长度',
    enterValidWeight: '请填写有效的重量',
    saveFailed: '保存失败',
    switchCamera: '切换摄像头',
    initializingCamera: '正在初始化相机...',
    retake: '重拍',
    enterSpeciesName: '输入鱼种名称',
    enterLength: '输入长度',
    optional: '可选',
    estimated: '预估',
    estimatedWeight: '预估重量',
    enterActualWeight: '输入实际重量',
    useEquipment: '使用装备',
    modify: '修改',
    catchLocation: '钓获地点',
    catchTime: '钓获时间',
    confirmSave: '确认入库',
    cameraPermissionRequired: '需要相机权限才能拍照',
    noCameraFound: '未找到可用的相机',
    cameraInitFailed: '相机初始化失败',
    cameraControllerInitFailed: '相机控制器初始化失败',
    cameraTakePictureFailed: '拍照失败',
    centimeter: '厘米',
    inch: '英寸',
    kilogram: '千克',
    pound: '磅',
    meter: '米',
    foot: '英尺',
    gram: '克',
    ounce: '盎司',
    kilometer: '千米',
    mile: '英里',
    celsius: '摄氏度',
    fahrenheit: '华氏度',
    temperature: '温度',
    millimeter: '毫米',
    unitsSettings: '单位设置',
    followSystem: '跟随系统',
    off: '关闭',
    on: '开启',
    simplifiedChinese: '简体中文',
    enabled: '已开启',
    disabled: '已关闭',
    locationManagement: '钓点管理',
    locationManagementDesc: '管理钓点，合并相似钓点',
    speciesManagement: '品种管理',
    speciesManagementDesc: '管理鱼种，编辑常用鱼种',
    aiConfiguration: 'AI配置',
    aiConfigurationDesc: '配置AI识别功能',
    exportAndBackupManagement: '导出与备份',
    exportAndBackupManagementDesc: '导出数据或备份到云端',
    syncToCloud: '同步到云端',
    exportToLocal: '导出到本地文件',
    importFromLocal: '从本地文件导入',
    appDescription: '一款专为钓鱼爱好者设计的鱼获记录工具。',
    features: '功能特点：',
    gotIt: '知道了',
    webdavSettings: 'WebDAV 设置',
    noAchievementData: '暂无成就数据',
    completed: '已完成',
    specialAchievement: '特殊成就',
    completion: '完成度',
    achievementOverview: '成就总览',
    unlocked: '已解锁',
    totalAchievements: '总成就',
    achievementUnit: '个成就',
    remainingAchievements: r'还需要 $count 项成就',
    noAchievements: '暂无成就',
    achieved: '已达成',
    editEquipment: '编辑装备',
    addEquipment: '添加装备',
    basicInfo: '基本信息',
    brand: '品牌',
    brandHint: '达亿瓦、Shimano',
    model: '型号',
    modelHint: '如：波纹二代',
    price: '价格',
    priceHint: '如：1999',
    invalidPrice: '请输入有效价格',
    priceTooHigh: '价格不能超过100万',
    purchaseDate: '购买日期',
    tapToSelect: '点击选择',
    setDefault: '设为默认装备',
    autoAssociate: '记录渔获时自动关联',
    rodParameters: '鱼竿参数',
    gunHandle: '枪柄',
    spinningHandle: '直柄',
    handleType: '握柄类型',
    handleTypeHint: '枪柄/直柄',
    usageType: '用途类型',
    selectOrEnterUsage: '选择或输入用途',
    reelParameters: '渔轮参数',
    baitcaster: '水滴轮',
    spinningReel: '纺车轮',
    reelType: '轮型',
    reelTypeHint: '水滴轮/纺车轮',
    reelUsageHint: '远投/泛用/微物',
    lineInfo: '鱼线信息',
    brandAndName: '品牌及名称',
    lineBrandHint: '如：YGK、Varivas',
    lineNumber: '线号',
    lineNumberHint: '如：0.8号',
    lineLength: '线长',
    lineLengthHint: '如：150m',
    lineDate: '上线时间',
    lureParameters: '鱼饵参数',
    type: '类型',
    selectOrEnterType: '选择或输入类型',
    myEquipment: '我的装备',
    expandAll: '全部展开',
    collapseAll: '全部收起',
    noEquipmentYet: '还没有',
    noEquipmentAddHint: '暂无，点击管理装备添加',
    confirmDeleteEquipment: '确定要删除该装备吗？',
    defaultLabel: '默认',
    unnamed: '未命名',
    record: '战绩',
    selectEquipment: '选择装备',
    manageEquipment: '管理装备',
    notSelected: '未选择',
    lengthHint: '如：1.8m',
    sections: '节数',
    sectionsHint: '如：2',
    material: '材质',
    materialHint: '如：碳素',
    hardness: '硬度',
    hardnessHint: '如：UL/L/M/MH/H',
    action: '调性',
    actionHint: '如：快调/中调/慢调',
    weightRangeHint: '如：1-7g',
    bearings: '轴承数',
    bearingsHint: '如：6+1',
    jointType: '插接方式',
    jointTypeHint: '如：插节/拔节',
    ratio: '速比',
    ratioHint: '如：5.2:1',
    ratioFront: '前',
    ratioBack: '后',
    capacityHint: '如：0.8/150',
    capacityLineUnit: '号/',
    brakeTypeHint: '如：磁力刹车/离心刹车',
    lineType: '线种',
    lineTypeHint: '如：PE线/尼龙线/碳线',
    lureTypeHint: '如：米诺/VIB/软虫/亮片',
    lureWeightHint: '如：7g/10g/14g',
    lureSizeHint: '如：5cm/7cm/10cm',
    lureColorHint: '如：银色/金色/荧光绿',
    size: '尺寸',
    selectAtLeast2Locations: '请至少选择2个钓点进行合并',
    confirmMerge: '确认合并',
    mergeLocationsTo: '将以下钓点合并为：',
    mergedLocations: '合并的钓点：',
    mergeSuccess: '合并成功',
    mergeFailed: '合并失败',
    noAutoMergeLocations: '没有发现可自动合并的钓点',
    autoMerge: '自动合并',
    found: '发现',
    similarLocations: '组相似钓点',
    mergeTo: '合并为',
    mergeAll: '全部合并',
    autoMergeSuccess: '自动合并成功',
    autoMergeFailed: '自动合并失败',
    mergeSelected: '合并选中',
    groups: '组',
    noLocationRecords: '暂无钓点记录',
    enableWatermark: '启用水印',
    watermarkPosition: '水印显示在照片左下角',
    selectWatermarkInfo: '选择水印上显示的信息',
    watermarkPreview: '水印预览',
    watermarkPositionDesc: '水印显示在照片左下角，位置固定',
    watermarkPositionTopLeft: '水印显示在照片左上角',
    watermarkPositionTopRight: '水印显示在照片右上角',
    watermarkPositionBottomLeft: '水印显示在照片左下角',
    watermarkPositionBottomRight: '水印显示在照片右下角',
    watermarkPositionCenter: '水印显示在照片居中位置',
    // Watermark Settings Page
    watermarkDragToSort: '长按拖拽可排序',
    watermarkNotEnabled: '未启用',
    watermarkStyle: '水印样式',
    watermarkBgRadius: '背景圆角',
    watermarkBgOpacity: '背景透明度',
    watermarkFontSize: '字体大小',
    watermarkTemplateSimple: '简约',
    watermarkTemplateSimpleDesc: '左下角简洁呈现',
    watermarkTemplateElegant: '优雅',
    watermarkTemplateElegantDesc: '右下角深色磨砂',
    watermarkTemplateBold: '大字',
    watermarkTemplateBoldDesc: '居中醒目高对比',
    watermarkTemplate: '模板',
    watermarkColorWhite: '白色',
    watermarkColorBlack: '黑色',
    watermarkColorRed: '红色',
    watermarkColorGreen: '绿色',
    watermarkColorBlue: '蓝色',
    watermarkColorYellow: '黄色',
    watermarkColorPurple: '紫色',
    watermarkColorCyan: '青色',
    watermarkFontColor: '字体颜色',
    watermarkPositionTopLeftLabel: '左上',
    watermarkPositionTopRightLabel: '右上',
    watermarkPositionBottomLeftLabel: '左下',
    watermarkPositionBottomRightLabel: '右下',
    watermarkPositionCenterLabel: '居中',
    watermarkPositionLabel: '水印位置',
    watermarkCustomText: '自定义文字',
    watermarkCustomTextHint: '显示在水印底部（如个人签名）',
    watermarkCustomTextPlaceholder: '选填，例如：个性签名',
    watermarkPreviewSpecies: '鳜鱼',
    watermarkPreviewLocation: '杭州西湖',
    sharePreview: '分享预览',
    resetPosition: '重置',
    confirmShare: '确认分享',
    dragToAdjustWatermark: '拖拽水印调整位置',
    pinchToZoomWatermark: '双指捏合缩放水印',
    rodDistribution: '鱼竿分布',
    reelDistribution: '渔轮分布',
    lureDistribution: '鱼饵分布',
    statistics: '统计数据',
    catchStatistics: '渔获统计',
    shareFailed: '分享失败',
    confirmDeleteFish: '确定要删除这条鱼获记录吗？',
    notFilled: '未填写',
    editFish: '编辑鱼获',
    mapLocation: '钓点地图',
    errorCameraPermission: '需要相机权限才能使用拍照功能',
    errorCameraInit: '相机初始化失败，请重启应用',
    errorCameraSwitch: '切换摄像头失败',
    errorLocationPermission: '需要位置权限才能记录钓点',
    errorLocationFetch: '获取位置信息失败',
    errorDatabaseRead: '读取数据失败',
    errorDatabaseWrite: '保存数据失败',
    errorFileDelete: '删除文件失败',
    errorFileExport: '导出文件失败',
    errorFileImport: '导入文件失败',
    errorNetworkConnect: '网络连接失败',
    errorWebDAVConnect: 'WebDAV连接失败',
    errorWebDAVUpload: '上传到WebDAV失败',
    errorWebDAVDownload: '从WebDAV下载失败',
    errorShareFailed: '分享失败',
    errorSaveFailed: '保存失败',
    errorLoadFailed: '加载失败',
    errorDeleteFailed: '删除失败',
    errorUnknown: '发生未知错误',
    rodHandleTypes: ['枪柄', '直柄'],
    rodUsageTypes: ['微物马口竿', '泛用综合竿', '远投翘嘴竿', '虫竿/鳜鱼竿', '鲈钓竿', '雷强打黑竿'],
    reelTypes: ['水滴轮', '纺车轮'],
    reelUsageTypes: ['远投', '泛用', '微物', '雷强', '铁板/慢摇'],
    lureTypeOptions: [
      '米诺',
      '波爬',
      '铅笔',
      '亮片',
      '软虫',
      '铁板',
      'VIB',
      '摇摆饵',
      '其他',
    ],
    unknownEquipment: '未知',
    equipmentOverview: '装备概览',
    totalEquipment: '总计',
    brandDistribution: '品牌分布',
    equipmentCatchStats: '装备战绩',
    equipmentId: '装备',
    quantityStats: '数量统计',
    equipmentCatchRanking: '装备战绩榜',
    noCatchData: '暂无战绩数据',
    selectFromGallery: '从相册选择',
    zoomIn: '放大',
    zoomOut: '缩小',
    locateMe: '定位到我的位置',
    noLocationCoordinates: '暂无钓点坐标',
    noLocationCoordinatesHint: '记录渔获时开启定位即可显示',
    lastVisit: '最后访问',
    noRecords: '暂无记录',
    coordinates: '坐标',
    navigate: '导航',
    cannotOpenMapApp: '无法打开地图应用',
    locationPermissionDenied: '位置权限未授权',
    locationTimeout: '定位超时',
    geocodingTimeout: '地址解析超时',
    unknownLocation: '未知位置',
    catchCount: '渔获数量',
    exportFormat: '导出格式',
    csvTable: 'CSV 表格',
    csvDescription: '适用于 Excel/数据分析',
    jsonFullBackup: 'JSON 完整备份',
    jsonDescription: '包含所有数据的完整备份',
    exportingCsv: '正在导出 CSV...',
    csvExportSuccess: 'CSV 导出成功',
    generationFailed: '生成失败',
    exportingJson: '正在导出 JSON...',
    lureboxBackup: 'LureBox 备份',
    exporting: '正在导出',
    generatingCsvFile: '正在生成 CSV 文件...',
    exportConfirm: '导出确认',
    confirmExport: '确认导出',
    willExportNRecords: r'将导出 $count 条记录',
    exportOptions: '导出选项',
    format: '格式',
    yes: '是',
    no: '否',
    previewFirstN: r'预览 (前 $count 条)',
    moreRecordsRemaining: r'... 还有 $count 条记录',
    exportNRecords: r'导出 $count 条记录',
    noMatchingRecords: '没有符合条件的记录',
    allTime: '全部时间',
    startDate: '开始',
    now: '现在',
    timeRange: '时间范围',
    speciesFilter: '品种筛选',
    clear: '清除',
    otherOptions: '其他选项',
    includeImagePaths: '包含图片路径',
    includeLocationInfo: '包含位置信息',
    confirmImportFile: '确认导入数据？',
    importingData: '正在导入...',
    importedCount: r'导入了 $count 条记录',
    pleaseFillCompleteInfo: '请填写完整信息',
    uploading: '正在上传...',
    enumerationSeparator: '、',
    catchRecordsExport: '鱼获记录导出',
    allRecords: '全部记录',
    dateRangeTo: '至',
    // UI Labels
    address: '地址',
    weather: '天气',
    tapToSet: '点击设置',
    pendingRecognition: '待识别',
    addToPendingRecognition: '⏭ 加入待识别',
    cancelPendingRecognition: '↩ 取消待识别',
    ascending: '升序',
    descending: '降序',
    noEquipment: '暂无装备',
    hideLocation: '隐藏钓点',
    showLocation: '显示钓点',
    totalCountPattern: '合计 %d 条',
    speciesCountPattern: '%s: %d条',
    rodUnit: '支',
    reelUnit: '只',
    lureUnit: '种',
    configureRig: '配置钓组',
    rigType: '钓组类型',
    sinkerConfig: '插铅配置',
    sinkerWeight: '插铅重量',
    sinkerPosition: '插铅位置',
    hookConfig: '鱼钩配置',
    hookWeight: '鱼钩重量',
    hookSize: '钩号',
    customOption: '自定义',
    customRigTypeHint: '输入自定义钓组类型',
    customHookTypeHint: '输入自定义鱼钩类型',
    pendingFishCountPattern: '你有 %d 条鱼获待识别品种',
    goToSpeciesManagement: '点击前往品种管理',
    airTemperature: '气温',
    pressure: '气压',
    weatherInfo: '天气信息',
    // 天气描述（WMO）
    weatherClear: '晴',
    weatherMainlyClear: '晴间多云',
    weatherPartlyCloudy: '多云',
    weatherOvercast: '阴',
    weatherFog: '雾',
    weatherDrizzle: '小雨',
    weatherFreezingDrizzle: '冻雨',
    weatherRain: '中雨',
    weatherFreezingRain: '雨夹雪',
    weatherSnowFall: '大雪',
    weatherSnowGrains: '雪粒',
    weatherRainShowers: '暴雨',
    weatherSnowShowers: '阵雪',
    weatherThunderstorm: '雷暴',
    weatherThunderstormHail: '雷暴加冰雹',
    weatherUnknown: '未知',
    // 天气选项
    weatherOption0: '☀️ 晴',
    weatherOption1: '⛅ 晴间多云',
    weatherOption2: '☁️ 多云',
    weatherOption3: '🌧️ 小雨',
    weatherOption4: '⛈️ 雷暴',
    weatherOption5: '❄️ 雪',
    weatherOption6: '🌫️ 雾',
    // 相机/编辑页面
    modifyCatchLocation: '修改钓获地点',
    locationName: '地点名称',
    modifyWeather: '修改天气信息',
    notSet: '未设置',
    onboardingSkip: '跳过',
    onboardingGetStarted: '开始使用',
    onboardingNext: '下一步',
    onboardingWelcomeTitle: '欢迎使用路亚鱼护',
    onboardingWelcomeDesc: '记录每一次出钓的渔获',
    onboardingFeaturesTitle: '功能介绍',
    onboardingFeatureCameraTitle: '拍照记录',
    onboardingFeatureCameraDesc: '快速拍摄鱼获照片',
    onboardingFeatureEquipmentTitle: '装备管理',
    onboardingFeatureEquipmentDesc: '管理鱼竿、鱼轮、鱼饵',
    onboardingFeatureStatsTitle: '统计分析',
    onboardingFeatureStatsDesc: '查看捕获数据趋势',
    onboardingFeatureBackupTitle: '数据备份',
    onboardingFeatureBackupDesc: '云端备份永不丢失',
    onboardingPermissionsTitle: '权限说明',
    onboardingPermissionCameraTitle: '相机权限',
    onboardingPermissionCameraDesc: '用于拍摄鱼获照片',
    onboardingPermissionCameraExample: '示例: 拍照记录渔获精彩瞬间',
    onboardingPermissionLocationTitle: '位置权限',
    onboardingPermissionLocationDesc: '记录钓点位置信息',
    onboardingPermissionLocationExample: '示例: 自动记录钓点坐标',
    onboardingPrivacyNote: '我们不会收集或上传您的隐私数据',
    onboardingSettingsTitle: '个性化设置',
    onboardingSettingsDesc: '可以在设置中随时调整',
    onboardingSettingsItems: '单位制、主题、语言',
    onboardingReadyTitle: '准备就绪!',
    onboardingReadyDesc: '开始记录您的第一个渔获吧',
    onboardingPermissionsGrant: '授权权限',
    onboardingPermissionsRequesting: '正在请求权限...',
    onboardingPermissionsGranted: '权限已授权',
    recognize: '识别',
    notUsing: '不使用',
    sharing: '正在分享...',
    distribution: '分布',
    fishListTitle: '鱼获列表',
    invalidFishId: '无效的渔获ID',
    fishNotFound: '渔获未找到',
    discardChanges: '放弃更改？',
    discardChangesMessage: '您有未保存的更改，确定要离开吗？',
    aboutFeatureCatchTitle: '渔获记录',
    aboutFeatureCatchDesc: '拍照记录、GPS定位、天气信息',
    aboutFeatureEquipmentTitle: '装备管理',
    aboutFeatureEquipmentDesc: '鱼竿、渔轮、鱼饵全面管理',
    aboutFeatureStatsTitle: '数据统计',
    aboutFeatureStatsDesc: '趋势分析、物种分布、装备使用',
    aboutFeatureAITitle: 'AI识别',
    aboutFeatureAIDesc: '智能识别鱼种，自动填充信息',
    aboutFeatureWatermarkTitle: '图片水印',
    aboutFeatureWatermarkDesc: '自定义水印样式，分享精彩瞬间',
    aboutFeatureExportTitle: '数据导出',
    aboutFeatureExportDesc: '支持CSV、PDF导出与分享',
    aboutFeatureCloudTitle: '云备份',
    aboutFeatureCloudDesc: 'WebDAV同步，数据安全无忧',
    aboutFeatureAchievementTitle: '成就系统',
    aboutFeatureAchievementDesc: '解锁成就，记录钓鱼里程碑',
    aboutCopyright: '© 2026 LureBox 路亚鱼护',
    locationCancelSelect: '取消选择',
    locationMergeTo: '合并到',
    locationEnterTargetName: '输入目标名称',
    locationCount: '钓点数量',
    locationTotalFishCount: '总渔获数',
    locationSmartMergeSuggestion: '智能合并建议',
    locationStartFishing: '开始记录您的钓鱼活动吧',
    locationEditName: '修改钓点名称',
    locationNewName: '新名称',
    locationEnterNewName: '输入新的钓点名称',
    locationEditSuccess: '修改成功',
    locationEditFailed: '修改失败',
    locationMergeConfirm: '确认合并',
    locationConfirmAutoMerge: '确认自动合并',
    locationAutoMergeConfirm: '将 %d 个相似钓点合并为 "%s"，合并后无法撤销',
    locationSearchHint: '搜索钓点',
    speciesManualRecognition: '手动识别',
    speciesAssignToCatches: '为以下鱼获指定品种：',
    speciesNameLabel: '品种名称',
    speciesConfirm: '确认',
    speciesAiResult: 'AI 识别结果：%s',
    speciesConfidence: '置信度：%.1f%%',
    speciesEditableName: '品种名称（可修改）',
    speciesRename: '重命名品种',
    speciesEnterNewName: '输入新物种名称',
    speciesConfirmDelete: '确认删除',
    speciesDeleteConfirmMsg: '确定要删除品种 "%s" 吗？相关渔获记录将变为未知品种。',
    speciesUpdated: '已更新品种: %s',
    speciesUpdateFailed: '更新失败',
    speciesRenamed: '已将 "%s" 重命名为 "%s"',
    speciesRenameFailed: '重命名失败',
    speciesDeleted: '已删除品种 "%s" (%d 条记录)',
    speciesDeleteFailed: '删除失败',
    speciesNoRecords: '暂无品种记录',
    speciesRecognitionComplete: '识别完成: %d 条成功, %d 条失败',
    speciesSaved: '已保存品种',
    speciesImageNotFound: '图片不存在',
    speciesConfigureApiKey: '请先配置 AI 识别 API Key',
    speciesAiResultTitle: 'AI 识别结果',
    speciesAlternative: '备选',
    speciesNoResult: '未能识别出结果',
    speciesRecognitionFailed: '识别失败: %s',
    aiConfigTitle: 'AI 配置',
    aiProviderLabel: 'AI 提供商',
    aiCurrentProvider: '当前使用的 AI 提供商',
    aiConfigured: '已配置',
    aiNotConfigured: '未配置',
    aiConfigureProvider: '配置 %s',
    aiEnterApiKey: '输入您的 API Key',
    aiPleaseEnterApiKey: '请输入 API Key',
    aiBaseUrlRequired: 'Base URL（必填）',
    aiBaseUrlOptional: 'Base URL（可选）',
    aiOpenaiEndpointRequired: 'OpenAI 兼容 API 端点，必填',
    aiCustomRequiresBaseUrl: '自定义提供商必须填写 Base URL',
    aiModelNameOptional: 'Model Name（可选）',
    aiSpecifyModelName: '指定使用的模型名称',
    aiTestConnection: '测试连接',
    aiSaving: '保存中...',
    aiConnectionSuccess: '连接成功！API Key 有效。',
    aiConnectionFailed: '连接失败: %s',
    aiConfigSaved: '配置已保存',
    pendingRecognitionList: '待识别列表',
    pendingNoFish: '暂无待识别鱼获',
    pendingAiRecognition: 'AI识别',
    pendingManual: '手动',
    pendingRecognizing: '正在识别中...',
    pendingRecognitionProgress: '识别中: %d/%d (成功: %d, 失败: %d)',
    pendingBatchRecognition: '批量AI识别',
    pendingFishCount: '%d条',
    deleteSuccess: '删除成功',
    exportFailedMsg: '导出失败',
    fullBackupTitle: '完整备份',
    fullBackupCreateDesc: '将创建包含数据库和所有照片的完整备份，文件保存到设备本地存储。',
    startBackup: '开始备份',
    creatingBackup: '正在创建备份',
    backupRunning: '备份正在后台运行，请稍候...',
    backupComplete: '备份已完成，文件已保存到本地存储。',
    backupFailed: '备份失败',
    restoreTitle: '恢复备份',
    restoreOverwriteWarning: '恢复备份将覆盖当前所有数据，此操作不可撤销。确定要继续吗？',
    continueAction: '继续',
    restoreSuccessMsg: '恢复成功',
    restoreFailedMsg: '恢复失败',
    restoreDetailPattern: '渔获: %d 条 / 装备: %d 件 / 照片: %d 张',
    csvExport: 'CSV 导出',
    jsonExport: 'JSON 导出',
    lureboxCompleteBackup: 'LureBox 完整备份',
    lureboxDataExport: 'LureBox 数据导出',
    uploadingToCloud: '上传中...',
    backupUploaded: '备份已上传到云端',
    uploadFailed: '上传失败',
    testing: '测试中...',
    webdavTitle: 'WebDAV 备份',
    webdavConfigureServer: '配置 WebDAV 服务器以启用云端备份功能',
    webdavSupportedUrl: '支持 WebDAV 协议的 URL',
    webdavPleaseEnterAddress: '请输入服务器地址',
    webdavUrlMustStartHttp: 'URL 必须以 http:// 或 https:// 开头',
    webdavPleaseEnterUsername: '请输入用户名',
    webdavPleaseEnterPassword: '请输入密码',
    backupNow: '立即备份',
    testFailed: '测试失败',
    cameraInitTimeout: '相机初始化超时',
    speciesHistoryTimeout: '加载物种历史超时',
    equipmentLoadTimeout: '加载装备超时',
    locationFetchTimeout: '获取位置超时',
    saveFailedCheckInput: '保存失败，请检查输入',
    saveFailedRetry: '保存失败，请重试',
    savedLabel: '已设置',
    notSavedLabel: '未设置',
    errorDeviceLocationOff: '请开启设备定位服务',
    errorContextInvalid: '上下文已失效',
    errorPermanentlyDenied: '已被永久拒绝，请在系统设置中开启',
    errorDenied: '被拒绝，需要在系统设置中开启',
    errorRejected: '被拒绝',
    permissionRequiredTitle: '需要%s',
    permissionOpenSettings: '打开设置',
    privacyNote: '我们不会收集或上传您的数据，所有信息都保存在本地设备上。',
    permissionGrantLater: '暂不授权',
    permissionGrant: '授权',
    unknownSpecies: '未知物种',
    errorImageNotFound: '图片文件不存在',
    errorImageTooLarge: '图片大小超过10MB限制',
    errorUnsupportedFormat: '不支持的图片格式，请使用 JPG、PNG 或 WebP',
    errorApiKeyNotConfigured: '未配置 API 密钥',
    errorProviderDisabled: '当前提供商已禁用',
    errorUnknownProvider: '未知的识别提供商',
    similarLocationsLabel: '相似钓点：',
    containsNSimilarLocations: '包含 %d 个相似钓点',
    mergeButton: '合并',
    fishCountSuffix: '%d 条渔获',
    locationFailed: '定位失败',
    unlockProgress: '解锁进度',
    speciesCountPattern2: '%d / %d 种鱼',
    monthlyNewSpecies: '本月新增: +%d 种',
    categoryQuantity: '数量类',
    categorySize: '尺寸类',
    categorySpecies: '品种类',
    categoryLocation: '地点类',
    categoryEquipment: '装备类',
    categoryEco: '环保类',
    rodSection1: '1节',
    rodSection2: '2节',
    rodSection3: '3节',
    rodSectionMulti: '多节',
    jointMethod: '插节方式',
    jointTypeSpigot: '正并继',
    jointTypeReverseSpigot: '逆并继',
    jointTypeDragonSpigot: '印龙继',
    jointTypeTelescopic: '伸缩',
    rodActionSS: 'SS调（超慢调）',
    rodActionS: 'S调（慢调）',
    rodActionMR: 'MR调（中慢调）',
    rodActionR: 'R调（中调）',
    rodActionRF: 'RF调（中快调）',
    rodActionF: 'F调（快调）',
    rodActionFF: 'FF调（超快调）',
    rodActionXF: 'XF调（极快调）',
    baitWeightLabel: '适合饵重',
    minValue: '最小值',
    maxValue: '最大值',
    lineLabel: '线号',
    lineCapacity: '长度',
    brakeTypeTraditionalMagnetic: '传统磁力刹车',
    brakeTypeCentrifugal: '离心刹车',
    brakeTypeDC: 'DC刹车',
    brakeTypeFloatingMagnetic: '浮动磁力刹车',
    brakeTypeInnovative: '创新组合刹车',
    quantityUnitPiece: '条',
    quantityUnitItem: '只',
    quantityUnitPack: '个',
    quantityUnitBox: '包',
    quantityUnitCarton: '盒',
    cardJointMethod: '插节方式',
    cardAction: '动作',
    cardStrength: '强度',
    cardColor: '颜色',
    quantityPrefix: '数量: ',
    typeSpinningRod: '纺车竿',
    typeBaitcastingRod: '水滴竿',
    typeFlyRod: '飞蝇竿',
    typeTrollingRod: '拖钓竿',
    typeSpinningReel: '纺车轮',
    typeBaitcastingReel: '水滴轮',
    typeFlyReel: '飞蝇轮',
    typeTrollingReel: '拖钓轮',
    typeHardBait: '硬饵',
    typeSoftBait: '软饵',
    typeSpoon: '亮片',
    typeJigHead: '铅头钩',
    typeNylonLine: '尼龙线',
    typePELine: 'PE线',
    typeFluorocarbonLine: '碳线',
    countSuffix: '条',
    distributionTitle: '分布',
    priceDistribution: '价格分布',
  );

