import '../models/achievement.dart';

/// 成就配置
class AchievementConfig {
  AchievementConfig._();

  /// 所有成就定义
  static const List<AchievementDefinition> definitions = [
    // ==================== 数量类 ====================
    AchievementDefinition(
      id: 'catch_first',
      title: '初次入坑',
      description: '记录第1条鱼获',
      icon: '🎣',
      level: AchievementLevel.bronze,
      category: '数量类',
      target: 1,
    ),
    AchievementDefinition(
      id: 'catch_10',
      title: '十全十美',
      description: '累计10条鱼获',
      icon: '🏆',
      level: AchievementLevel.silver,
      category: '数量类',
      target: 10,
    ),
    AchievementDefinition(
      id: 'catch_100',
      title: '百条俱乐部',
      description: '累计100条鱼获',
      icon: '🏅',
      level: AchievementLevel.gold,
      category: '数量类',
      target: 100,
    ),
    AchievementDefinition(
      id: 'catch_500',
      title: '五百突破',
      description: '累计500条鱼获',
      icon: '💎',
      level: AchievementLevel.gold,
      category: '数量类',
      target: 500,
    ),
    AchievementDefinition(
      id: 'catch_1000',
      title: '钓王之路',
      description: '累计1000条鱼获',
      icon: '👑',
      level: AchievementLevel.platinum,
      category: '数量类',
      target: 1000,
    ),

    // ==================== 尺寸类 ====================
    AchievementDefinition(
      id: 'length_30',
      title: '30cm突破',
      description: '首次钓获≥30cm的鱼',
      icon: '📏',
      level: AchievementLevel.bronze,
      category: '尺寸类',
      target: 1,
    ),
    AchievementDefinition(
      id: 'length_50',
      title: '50cm俱乐部',
      description: '首次钓获≥50cm的鱼',
      icon: '🐟',
      level: AchievementLevel.silver,
      category: '尺寸类',
      target: 1,
    ),
    AchievementDefinition(
      id: 'length_70',
      title: '巨物出水',
      description: '首次钓获≥70cm的鱼',
      icon: '👑',
      level: AchievementLevel.gold,
      category: '尺寸类',
      target: 1,
    ),
    AchievementDefinition(
      id: 'length_90',
      title: '超级巨物',
      description: '首次钓获≥90cm的鱼',
      icon: '🏆',
      level: AchievementLevel.gold,
      category: '尺寸类',
      target: 1,
    ),
    AchievementDefinition(
      id: 'length_120',
      title: '传说级巨物',
      description: '首次钓获≥120cm的鱼',
      icon: '⚔️',
      level: AchievementLevel.platinum,
      category: '尺寸类',
      target: 1,
    ),

    // ==================== 品种类 ====================
    AchievementDefinition(
      id: 'species_3',
      title: '鱼种收集者',
      description: '记录3种不同鱼种',
      icon: '🐠',
      level: AchievementLevel.bronze,
      category: '品种类',
      target: 3,
    ),
    AchievementDefinition(
      id: 'species_5',
      title: '鱼种达人',
      description: '记录5种不同鱼种',
      icon: '🐡',
      level: AchievementLevel.silver,
      category: '品种类',
      target: 5,
    ),
    AchievementDefinition(
      id: 'species_10',
      title: '鱼种大师',
      description: '记录10种不同鱼种',
      icon: '🦈',
      level: AchievementLevel.gold,
      category: '品种类',
      target: 10,
    ),
    AchievementDefinition(
      id: 'species_15',
      title: '鱼种专家',
      description: '记录15种不同鱼种',
      icon: '🐋',
      level: AchievementLevel.gold,
      category: '品种类',
      target: 15,
    ),
    AchievementDefinition(
      id: 'species_20',
      title: '鱼种百科全书',
      description: '记录20种不同鱼种',
      icon: '🦣',
      level: AchievementLevel.platinum,
      category: '品种类',
      target: 20,
    ),

    // ==================== 装备类 ====================
    AchievementDefinition(
      id: 'equipment_full',
      title: '装备齐全',
      description: '配齐竿/轮/饵全套装备',
      icon: '🎯',
      level: AchievementLevel.bronze,
      category: '装备类',
      target: 1,
    ),
    AchievementDefinition(
      id: 'equipment_5',
      title: '装备玩家',
      description: '添加10件装备',
      icon: '💎',
      level: AchievementLevel.silver,
      category: '装备类',
      target: 10,
    ),
    AchievementDefinition(
      id: 'equipment_10',
      title: '装备收藏家',
      description: '添加20件装备',
      icon: '🏆',
      level: AchievementLevel.gold,
      category: '装备类',
      target: 20,
    ),
    AchievementDefinition(
      id: 'equipment_20',
      title: '装备达人',
      description: '添加30件装备',
      icon: '💰',
      level: AchievementLevel.gold,
      category: '装备类',
      target: 30,
    ),
    AchievementDefinition(
      id: 'equipment_50',
      title: '装备大亨',
      description: '添加50件装备',
      icon: '🏰',
      level: AchievementLevel.platinum,
      category: '装备类',
      target: 50,
    ),

    // ==================== 地点类 ====================
    AchievementDefinition(
      id: 'location_3',
      title: '探索者',
      description: '记录3个不同钓点',
      icon: '🗺️',
      level: AchievementLevel.bronze,
      category: '地点类',
      target: 3,
    ),
    AchievementDefinition(
      id: 'location_10',
      title: '游钓达人',
      description: '记录10个不同钓点',
      icon: '🌍',
      level: AchievementLevel.silver,
      category: '地点类',
      target: 10,
    ),
    AchievementDefinition(
      id: 'location_20',
      title: '环球钓手',
      description: '记录20个不同钓点',
      icon: '🚀',
      level: AchievementLevel.gold,
      category: '地点类',
      target: 20,
    ),
    AchievementDefinition(
      id: 'location_30',
      title: '钓场开拓者',
      description: '记录30个不同钓点',
      icon: '🗿',
      level: AchievementLevel.gold,
      category: '地点类',
      target: 30,
    ),
    AchievementDefinition(
      id: 'location_50',
      title: '钓遍天下',
      description: '记录50个不同钓点',
      icon: '🌏',
      level: AchievementLevel.platinum,
      category: '地点类',
      target: 50,
    ),

    // ==================== 环保类 ====================
    AchievementDefinition(
      id: 'release_10',
      title: '环保卫士',
      description: '放流10条鱼',
      icon: '🌱',
      level: AchievementLevel.bronze,
      category: '环保类',
      target: 10,
    ),
    AchievementDefinition(
      id: 'release_rate_80',
      title: '生态守护者',
      description: '放流比例≥80%',
      icon: '💚',
      level: AchievementLevel.silver,
      category: '环保类',
      target: 1,
    ),
    AchievementDefinition(
      id: 'release_50',
      title: '放流大师',
      description: '放流50条鱼',
      icon: '🌲',
      level: AchievementLevel.silver,
      category: '环保类',
      target: 50,
    ),
    AchievementDefinition(
      id: 'release_100',
      title: '水中精灵',
      description: '放流100条鱼',
      icon: '🌳',
      level: AchievementLevel.gold,
      category: '环保类',
      target: 100,
    ),
    AchievementDefinition(
      id: 'release_200',
      title: '生态传奇',
      description: '放流200条鱼',
      icon: '🏞️',
      level: AchievementLevel.platinum,
      category: '环保类',
      target: 200,
    ),

    // ==================== 特殊成就 ====================
    AchievementDefinition(
      id: 'consecutive_7',
      title: '连续作战',
      description: '连续7天有鱼获记录',
      icon: '📅',
      level: AchievementLevel.silver,
      category: '特殊成就',
      target: 7,
    ),
    AchievementDefinition(
      id: 'monthly_30',
      title: '疯狂一个月',
      description: '单月记录30条鱼获',
      icon: '🔥',
      level: AchievementLevel.gold,
      category: '特殊成就',
      target: 30,
    ),
    AchievementDefinition(
      id: 'share_5',
      title: '分享达人',
      description: '分享5次鱼获',
      icon: '📤',
      level: AchievementLevel.silver,
      category: '特殊成就',
      target: 5,
    ),
    AchievementDefinition(
      id: 'new_record',
      title: '新纪录',
      description: '刷新个人最长鱼获纪录',
      icon: '🏆',
      level: AchievementLevel.gold,
      category: '特殊成就',
      target: 1,
    ),
    AchievementDefinition(
      id: 'daily_5',
      title: '极速连钓',
      description: '单日记录5条鱼获',
      icon: '⚡',
      level: AchievementLevel.silver,
      category: '特殊成就',
      target: 5,
    ),
    AchievementDefinition(
      id: 'morning_20',
      title: '晨钓达人',
      description: '上午6-9点记录20条鱼获',
      icon: '🌅',
      level: AchievementLevel.gold,
      category: '特殊成就',
      target: 20,
    ),
    AchievementDefinition(
      id: 'night_20',
      title: '夜钓之王',
      description: '晚上20-24点记录20条鱼获',
      icon: '🌙',
      level: AchievementLevel.gold,
      category: '特殊成就',
      target: 20,
    ),
    AchievementDefinition(
      id: 'photos_100',
      title: '拍照达人',
      description: '记录100张鱼获照片',
      icon: '📸',
      level: AchievementLevel.gold,
      category: '特殊成就',
      target: 100,
    ),
    AchievementDefinition(
      id: 'total_weight_10',
      title: '重量冠军',
      description: '累计鱼获总重超10kg',
      icon: '⚖️',
      level: AchievementLevel.gold,
      category: '特殊成就',
      target: 10,
    ),
    AchievementDefinition(
      id: 'equipment_combo_20',
      title: '装备联动大师',
      description: '使用同一套装备钓获20条鱼',
      icon: '🎖️',
      level: AchievementLevel.gold,
      category: '特殊成就',
      target: 20,
    ),
  ];
}

/// 成就定义
class AchievementDefinition {
  final String id;
  final String title;
  final String description;
  final String icon;
  final AchievementLevel level;
  final String category;
  final int target;

  const AchievementDefinition({
    required this.id,
    required this.title,
    required this.description,
    required this.icon,
    required this.level,
    required this.category,
    required this.target,
  });
}
